import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router";
import Alert from "../../../app/components/ui/alert/Alert";
import Badge from "../../../app/components/ui/badge/Badge";
import Input from "../../../app/components/forms/input/InputField";
import { createHoSoThamDinh, getDanhSachHoSoThamDinh, tiepNhanThamDinh } from "../api/xayDungVanBanApi";

const errorMessage = error => error?.response?.data?.message || error?.response?.data || error?.message || "Không thể tải dữ liệu.";
const dateText = value => value ? new Intl.DateTimeFormat("vi-VN").format(new Date(value)) : "-";
const statusInfo = status => status === "ChoTiepNhan" ? { label: "Chờ tiếp nhận", color: "warning" } : status === "DaTiepNhan" ? { label: "Đang thẩm định", color: "primary" } : { label: status === "DaHoanThanh" ? "Đã hoàn thành" : status, color: "success" };

export default function HoSoThamDinhListPage() {
  const navigate = useNavigate(); const [items, setItems] = useState([]), [search, setSearch] = useState(""), [error, setError] = useState(""), [loading, setLoading] = useState(true), [receivingId, setReceivingId] = useState("");
  const load = async () => { try { setLoading(true); setError(""); setItems(await getDanhSachHoSoThamDinh()); } catch (e) { setError(errorMessage(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const receiveSubmission = async item => { try { setReceivingId(item.hoSoId); setError(""); await createHoSoThamDinh(item.hoSoId); await tiepNhanThamDinh(item.hoSoId, { ngayTiepNhan: new Date().toISOString(), nguoiTiepNhanId: "00000000-0000-0000-0000-000000000000" }); navigate(`/xay-dung-van-ban/tham-dinh/${item.hoSoId}`, { state: { success: "Đã nhận hồ sơ trình và tạo hồ sơ thẩm định." } }); } catch (e) { setError(errorMessage(e)); } finally { setReceivingId(""); } };
  const shown = useMemo(() => { const q = search.trim().toLowerCase(); return q ? items.filter(x => [x.maHoSo, x.tenHoSo, x.tenDuThaoVanBan].some(v => v?.toLowerCase().includes(q))) : items; }, [items, search]);
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Hồ sơ thẩm định</h1><p className="mt-1 text-sm text-gray-500">Tiếp nhận, thẩm định và gửi kết quả cho cơ quan chủ trì.</p></div><button onClick={load} className="rounded-lg border px-4 py-2 text-sm">Tải lại</button></div>{error && <Alert variant="error" title="Không thể xử lý" message={error} />}<div className="overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-white/[0.05] dark:bg-white/[0.03]"><div className="border-b border-gray-100 px-5 py-4 dark:border-white/[0.05]"><div className="max-w-xl"><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm mã hồ sơ, tên hồ sơ, tên dự thảo..." /></div></div><div className="max-w-full overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-gray-100 dark:border-white/[0.05]"><th className="px-5 py-3 text-left text-xs font-medium text-gray-500">Hồ sơ</th><th className="px-5 py-3 text-left text-xs font-medium text-gray-500">Dự thảo</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Trạng thái</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Gửi / tiếp nhận</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Thao tác</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-white/[0.05]">{loading ? <tr><td colSpan="5" className="px-5 py-10 text-center text-sm text-gray-500">Đang tải dữ liệu...</td></tr> : shown.length ? shown.map(item => { const status = statusInfo(item.trangThai); return <tr key={item.hoSoId} className="hover:bg-gray-50 dark:hover:bg-white/[0.02]"><td className="px-5 py-4"><div className="font-medium text-gray-800 dark:text-white/90">{item.tenHoSo}</div><div className="mt-1 text-xs text-gray-500">{item.maHoSo} · Năm {item.namXayDung}</div></td><td className="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{item.tenDuThaoVanBan || "-"}</td><td className="px-5 py-4 text-center"><Badge size="sm" color={status.color}>{status.label}</Badge></td><td className="px-5 py-4 text-center text-xs text-gray-500">Gửi: {dateText(item.ngayGuiThamDinh)}<div>Nhận: {dateText(item.ngayTiepNhan)}</div></td><td className="px-5 py-4 text-center"><button disabled={receivingId === item.hoSoId} onClick={() => item.boHoSoId ? navigate(`/xay-dung-van-ban/tham-dinh/${item.hoSoId}`) : receiveSubmission(item)} className="rounded-lg px-3 py-2 text-xs font-medium text-brand-500 hover:bg-gray-100 disabled:opacity-50">{item.boHoSoId ? "Xử lý thẩm định" : receivingId === item.hoSoId ? "Đang nhận..." : "Nhận hồ sơ trình"}</button></td></tr>; }) : <tr><td colSpan="5" className="px-5 py-10 text-center text-sm text-gray-500">Chưa có hồ sơ nào được gửi thẩm định.</td></tr>}</tbody></table></div></div></div>;
}
