import { useEffect, useMemo, useState } from "react";
import { useLocation, useNavigate } from "react-router";
import Alert from "../../../app/components/ui/alert/Alert";
import Badge from "../../../app/components/ui/badge/Badge";
import Input from "../../../app/components/forms/input/InputField";
import { Modal } from "../../../app/components/ui/modal";
import { getDanhSachHoSoTrinhThamDinh, getHoSoNguonTrinhThamDinh } from "../api/xayDungVanBanApi";

const getErrorMessage = (error) => error?.response?.data?.message || error?.response?.data || error?.message || "Không thể tải dữ liệu.";
const formatDate = (value) => value ? new Intl.DateTimeFormat("vi-VN").format(new Date(value)) : "-";

export default function HoSoTrinhThamDinhListPage() {
  const navigate = useNavigate();
  const location = useLocation();
  const [items, setItems] = useState([]); const [sources, setSources] = useState([]); const [search, setSearch] = useState(""); const [sourceSearch, setSourceSearch] = useState("");
  const [loading, setLoading] = useState(true); const [loadingSources, setLoadingSources] = useState(false); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const load = async () => { try { setLoading(true); setError(""); setItems(await getDanhSachHoSoTrinhThamDinh()); } catch (e) { setError(getErrorMessage(e)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const openCreate = async () => { try { setOpen(true); setLoadingSources(true); setSourceSearch(""); setError(""); setSources(await getHoSoNguonTrinhThamDinh()); } catch (e) { setError(getErrorMessage(e)); } finally { setLoadingSources(false); } };
  const filteredItems = useMemo(() => { const q = search.trim().toLowerCase(); return q ? items.filter(x => [x.maHoSo, x.tenHoSo, x.tenDuThaoVanBan].some(v => v?.toLowerCase().includes(q))) : items; }, [items, search]);
  const filteredSources = useMemo(() => { const q = sourceSearch.trim().toLowerCase(); return q ? sources.filter(x => [x.maHoSo, x.tenHoSo, x.tenDuThaoVanBan].some(v => v?.toLowerCase().includes(q))) : sources; }, [sources, sourceSearch]);
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Hồ sơ trình thẩm định</h1><p className="mt-1 text-sm text-gray-500">Theo dõi, cập nhật và gửi các hồ sơ đề nghị thẩm định.</p></div><button type="button" onClick={openCreate} className="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white">+ Tạo hồ sơ trình thẩm định</button></div>
    {error && <Alert variant="error" title="Không thể xử lý" message={error} />}
    {location.state?.success && <Alert variant="success" title="Hoàn tất" message={location.state.success} />}
    <div className="overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-white/[0.05] dark:bg-white/[0.03]"><div className="border-b border-gray-100 px-5 py-4 dark:border-white/[0.05]"><div className="max-w-xl"><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Tìm mã hồ sơ, tên hồ sơ, tên dự thảo..." /></div></div><div className="max-w-full overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-gray-100 dark:border-white/[0.05]"><th className="px-5 py-3 text-left text-xs font-medium text-gray-500">Hồ sơ</th><th className="px-5 py-3 text-left text-xs font-medium text-gray-500">Dự thảo</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Trạng thái</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Ngày lập / gửi</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Thao tác</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-white/[0.05]">{loading ? <tr><td colSpan="5" className="px-5 py-10 text-center text-sm text-gray-500">Đang tải dữ liệu...</td></tr> : filteredItems.length ? filteredItems.map(item => <tr key={item.boHoSoId} className="hover:bg-gray-50 dark:hover:bg-white/[0.02]"><td className="px-5 py-4"><div className="font-medium text-gray-800 dark:text-white/90">{item.tenHoSo}</div><div className="mt-1 text-xs text-gray-500">{item.maHoSo} · Năm {item.namXayDung}</div></td><td className="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{item.tenDuThaoVanBan}</td><td className="px-5 py-4 text-center"><Badge size="sm" color={item.trangThai === "DaGui" ? "success" : "warning"}>{item.trangThai === "DaGui" ? "Đã gửi" : "Đang nhập"}</Badge></td><td className="px-5 py-4 text-center text-sm text-gray-500">{formatDate(item.ngayTao)}{item.ngayGuiThamDinh && <div className="mt-1 text-xs">Gửi: {formatDate(item.ngayGuiThamDinh)}</div>}</td><td className="px-5 py-4 text-center"><div className="flex flex-wrap justify-center gap-1"><button type="button" onClick={() => window.open(`/admin/xay-dung-van-ban/ho-so/chi-tiet/${item.hoSoId}`, "_blank", "noopener,noreferrer")} className="rounded-lg px-3 py-2 text-xs font-medium text-gray-600 hover:bg-gray-100 hover:text-brand-500">Xem hồ sơ</button><button type="button" onClick={() => navigate(`/xay-dung-van-ban/trinh-tham-dinh/${item.hoSoId}`)} className="rounded-lg px-3 py-2 text-xs font-medium text-gray-600 hover:bg-gray-100 hover:text-brand-500">{item.trangThai === "DaGui" ? "Xem hồ sơ trình" : "Xem / cập nhật"}</button></div></td></tr>) : <tr><td colSpan="5" className="px-5 py-10 text-center text-sm text-gray-500">Chưa có hồ sơ trình thẩm định.</td></tr>}</tbody></table></div></div>
    <Modal isOpen={open} onClose={() => !loadingSources && setOpen(false)} className="max-w-4xl p-6"><div className="space-y-5"><div><h2 className="text-lg font-semibold text-gray-800 dark:text-white/90">Chọn hồ sơ nguồn để kế thừa</h2><p className="mt-1 text-sm text-gray-500">Chọn một hồ sơ đang ở bước soạn thảo. Tài liệu hiện hành của hồ sơ nguồn sẽ được kế thừa khi lập hồ sơ trình thẩm định.</p></div><Input value={sourceSearch} onChange={event => setSourceSearch(event.target.value)} placeholder="Tìm mã hồ sơ, tên hồ sơ, tên dự thảo..." />{loadingSources ? <div className="py-10 text-center text-sm text-gray-500">Đang tải hồ sơ nguồn...</div> : <div className="max-h-[50vh] overflow-y-auto divide-y rounded-lg border dark:border-white/[0.05]">{filteredSources.length ? filteredSources.map(source => <button type="button" key={source.hoSoId} onClick={() => navigate(`/xay-dung-van-ban/trinh-tham-dinh/${source.hoSoId}`)} className="flex w-full items-center justify-between gap-4 px-4 py-4 text-left hover:bg-gray-50 dark:hover:bg-white/[0.02]"><div><div className="font-medium text-gray-800 dark:text-white/90">{source.tenHoSo}</div><div className="mt-1 text-sm text-gray-500">{source.maHoSo} · {source.tenDuThaoVanBan} · Năm {source.namXayDung}</div></div><span className="shrink-0 rounded-lg border px-3 py-2 text-xs font-medium text-brand-500">Chọn kế thừa</span></button>) : <div className="p-8 text-center text-sm text-gray-500">Không có hồ sơ nguồn phù hợp để lập mới.</div>}</div>}<div className="flex justify-end"><button type="button" onClick={() => setOpen(false)} disabled={loadingSources} className="rounded-lg border px-4 py-2 text-sm font-medium">Đóng</button></div></div></Modal>
  </div>;
}
