// <auto-generated />
using System;
using KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KhaoSatThiHanhPhapLuatDbContext))]
    [Migration("20261007014029_AddSurveyReportSnapshots")]
    partial class AddSurveyReportSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kspl")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.BaoCaoKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CuocKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HanChe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KienNghi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgayBaoCao")
                        .HasColumnType("date");

                    b.Property<DateTime?>("NgayChot")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoKyHieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenBaoCao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UuDiem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuocKhaoSatId", "TrangThai");

                    b.ToTable("BaoCaoKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.CauHoiMauPhieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit");

                    b.Property<Guid>("CauHoiThongKeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChoPhepNhieuLuaChon")
                        .HasColumnType("bit");

                    b.Property<bool>("CoYKienTuDo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("MauPhieuKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MauSoTyLe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PHIEU_HOP_LE");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MauPhieuKhaoSatId", "MaCauHoi")
                        .IsUnique();

                    b.ToTable("CauHoiMauPhieus", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.CauHoiThongKe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ChoPhepNhieuLuaChon")
                        .HasColumnType("bit");

                    b.Property<bool>("CoYKienTuDo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CuocKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCauHoiThongKe")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MauSoTyLe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("PHIEU_HOP_LE");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuocKhaoSatId", "MaCauHoiThongKe")
                        .IsUnique();

                    b.ToTable("CauHoiThongKes", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.CauTraLoiKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiMauPhieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiThongKeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaTriSo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GiaTriText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LuaChonTraLoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PhieuNopKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SoLuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongSoTraLoi")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CauTraLoiKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.ChiTietBaoCaoKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaoCaoKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiThongKeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLuaChon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MauSoTyLe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoiDungCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungLuaChon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoLuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TyLe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YKienTuDo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaoCaoKhaoSatId", "CauHoiThongKeId", "MaLuaChon");

                    b.ToTable("ChiTietBaoCaoKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.CuocKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DenNgay")
                        .HasColumnType("date");

                    b.Property<Guid>("DonViChuTriId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KeHoachThiHanhPhapLuatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LinhVucId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaCuocKhaoSat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MucDich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhamVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCuocKhaoSat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("TuNgay")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MaCuocKhaoSat")
                        .IsUnique();

                    b.HasIndex("DonViChuTriId", "TrangThaiId", "CreatedAt");

                    b.ToTable("CuocKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.DoiTuongKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CanBoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CuocKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("HanNop")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MauPhieuKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NhomDoiTuongKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuocKhaoSatId", "DonViId")
                        .IsUnique();

                    b.ToTable("DoiTuongKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.LichSuXuLyKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuocKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DoiTuongKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NguoiXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PhieuNopKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGianXuLy")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuocKhaoSatId", "ThoiGianXuLy");

                    b.ToTable("LichSuXuLyKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.LoiImportKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PhieuNopKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoiImportKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.LuaChonTraLoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauHoiMauPhieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaLuaChon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CauHoiMauPhieuId", "MaLuaChon")
                        .IsUnique();

                    b.ToTable("LuaChonTraLois", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.MauPhieuKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CuocKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaPhatHanh")
                        .HasColumnType("bit");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("NhomDoiTuongKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PhienBan")
                        .HasColumnType("int");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NhomDoiTuongKhaoSatId", "PhienBan")
                        .IsUnique();

                    b.ToTable("MauPhieuKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.NhomDoiTuongKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CuocKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CuocKhaoSatId", "MaNhom")
                        .IsUnique();

                    b.ToTable("NhomDoiTuongKhaoSats", "kspl");
                });

            modelBuilder.Entity("KhaoSatThiHanhPhapLuatService.Infrastructure.Persistence.Entities.PhieuNopKhaoSat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoiTuongKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MauPhieuKhaoSatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayImport")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoiTuongKhaoSatId", "CreatedAt");

                    b.ToTable("PhieuNopKhaoSats", "kspl");
                });
#pragma warning restore 612, 618
        }
    }
}
