// <auto-generated />
using System;
using KhaiThacDuLieuService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhaiThacDuLieuService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KhaiThacDuLieuDbContext))]
    [Migration("20261010083147_AddCanhBaoLichSuXuLy")]
    partial class AddCanhBaoLichSuXuLy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoKhaiThacDuLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoiTuongNguon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DoiTuongNguonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViNhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChuXuLy")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("HanXuLy")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaCanhBao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayPhatSinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXem")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiNhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NhomCanhBao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThaiXuLy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoiTuongNguon", "DoiTuongNguonId", "MaCanhBao");

                    b.HasIndex("DonViNhanId", "TrangThaiXuLy", "NgayPhatSinh");

                    b.HasIndex("NguoiNhanId", "TrangThaiXuLy", "NgayPhatSinh");

                    b.HasIndex("NhomCanhBao", "TrangThaiXuLy", "NgayPhatSinh");

                    b.ToTable("CanhBaoKhaiThacDuLieus");
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoLichSuXuLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanhBaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DonViThucHienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("NguoiThucHienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NhacViecId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiSau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiTruoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CanhBaoId", "ThoiGian");

                    b.HasIndex("NhacViecId", "ThoiGian");

                    b.ToTable("CanhBaoLichSuXuLys");
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoNhacViec", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CanhBaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DonViGiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViNhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChuHoanThanh")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("HanXuLy")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MucDoUuTien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXem")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiGiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiNhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ThoiGianNhac")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CanhBaoId", "TrangThai", "HanXuLy");

                    b.HasIndex("DonViNhanId", "TrangThai", "HanXuLy");

                    b.HasIndex("NguoiNhanId", "TrangThai", "HanXuLy");

                    b.ToTable("CanhBaoNhacViecs");
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CauHinhCanhBaoKhaiThacDuLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KenhThongBao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaCanhBao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MucDoMacDinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NhomCanhBao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoNgayCanhBaoTruocHan")
                        .HasColumnType("int");

                    b.Property<string>("TenCanhBao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaCanhBao")
                        .IsUnique();

                    b.HasIndex("NhomCanhBao", "TrangThai");

                    b.ToTable("CauHinhCanhBaoKhaiThacDuLieus");
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.DangKyTrangThaiHoSoTraCuu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LaTrangThaiKetThuc")
                        .HasColumnType("bit");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MauHienThi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("DangKyTrangThaiHoSos", (string)null);
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanTraCuu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaKhoiTaoQuyTrinhXayDung")
                        .HasColumnType("bit");

                    b.Property<Guid>("DonViPheDuyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DuKienThoiGianTrinh")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoaiVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NamDangKy")
                        .HasColumnType("int");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenHoSo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenVanBanDuKien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrangThaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiVanBanId");

                    b.HasIndex("MaHoSo");

                    b.HasIndex("NamDangKy");

                    b.HasIndex("TrangThaiHoSoId");

                    b.HasIndex("DonViPheDuyetId", "TrangThaiHoSoId", "CreatedAt");

                    b.HasIndex("DonViSoanThaoId", "TrangThaiHoSoId", "CreatedAt");

                    b.ToTable("DangKyXayDungVanBans", (string)null);
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.DongBoKhaiThacDuLieuLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BatDauLuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KetThucLuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoaiDongBo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Loi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguonDuLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoBanGhi")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguonDuLieu", "LoaiDongBo", "BatDauLuc");

                    b.ToTable("DongBoKhaiThacDuLieuLogs");
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoLichSuXuLy", b =>
                {
                    b.HasOne("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoKhaiThacDuLieu", "CanhBao")
                        .WithMany("LichSuXuLys")
                        .HasForeignKey("CanhBaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoNhacViec", "NhacViec")
                        .WithMany("LichSuXuLys")
                        .HasForeignKey("NhacViecId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CanhBao");

                    b.Navigation("NhacViec");
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoNhacViec", b =>
                {
                    b.HasOne("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoKhaiThacDuLieu", "CanhBao")
                        .WithMany("NhacViecs")
                        .HasForeignKey("CanhBaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanhBao");
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoKhaiThacDuLieu", b =>
                {
                    b.Navigation("LichSuXuLys");

                    b.Navigation("NhacViecs");
                });

            modelBuilder.Entity("KhaiThacDuLieuService.Infrastructure.Persistence.Entities.CanhBaoNhacViec", b =>
                {
                    b.Navigation("LichSuXuLys");
                });
#pragma warning restore 612, 618
        }
    }
}
