import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router";
import Alert from "../../../app/components/ui/alert/Alert";
import Badge from "../../../app/components/ui/badge/Badge";
import Input from "../../../app/components/forms/input/InputField";
import { getCuocKhaoSats } from "../api/khaoSatThiHanhPhapLuatApi";

const formatDate = (value) => value ? new Intl.DateTimeFormat("vi-VN").format(new Date(value)) : "-";
const errorMessage = (error) => error?.response?.data?.message || error?.response?.data || error?.message || "Không thể tải danh sách cuộc khảo sát.";

export default function CuocKhaoSatListPage() {
  const navigate = useNavigate();
  const [items, setItems] = useState([]); const [keyword, setKeyword] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { try { setLoading(true); setError(""); const data = await getCuocKhaoSats({ keyword }); setItems(data.items || []); } catch (requestError) { setError(errorMessage(requestError)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const shown = useMemo(() => { const q = keyword.trim().toLocaleLowerCase("vi-VN"); return q ? items.filter((item) => [item.maCuocKhaoSat, item.tenCuocKhaoSat].some((value) => value?.toLocaleLowerCase("vi-VN").includes(q))) : items; }, [items, keyword]);
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Cuộc khảo sát</h1><p className="mt-1 text-sm text-gray-500">Quản lý hồ sơ cuộc khảo sát, mẫu phiếu và đơn vị được khảo sát.</p></div><button type="button" onClick={load} className="rounded-lg border px-4 py-2 text-sm font-medium">Tải lại</button></div>{error && <Alert variant="error" title="Có lỗi" message={error} />}<div className="overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-white/[0.05] dark:bg-white/[0.03]"><div className="border-b border-gray-100 px-5 py-4 dark:border-white/[0.05]"><div className="max-w-xl"><Input value={keyword} onChange={(event) => setKeyword(event.target.value)} onKeyDown={(event) => event.key === "Enter" && load()} placeholder="Tìm mã hoặc tên cuộc khảo sát..." /></div></div><div className="max-w-full overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-gray-100 dark:border-white/[0.05]"><th className="px-5 py-3 text-left text-xs font-medium text-gray-500">Cuộc khảo sát</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Thời gian</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Tiến độ nộp</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Thao tác</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-white/[0.05]">{loading ? <tr><td colSpan="4" className="px-5 py-10 text-center text-sm text-gray-500">Đang tải dữ liệu...</td></tr> : !shown.length ? <tr><td colSpan="4" className="px-5 py-10 text-center text-sm text-gray-500">Chưa có cuộc khảo sát.</td></tr> : shown.map((item) => <tr key={item.id} className="hover:bg-gray-50 dark:hover:bg-white/[0.02]"><td className="px-5 py-4"><div className="font-medium text-gray-800 dark:text-white/90">{item.tenCuocKhaoSat}</div><div className="mt-1 text-xs text-gray-500">{item.maCuocKhaoSat}</div></td><td className="px-5 py-4 text-center text-sm text-gray-600 dark:text-gray-300">{formatDate(item.tuNgay)} - {formatDate(item.denNgay)}</td><td className="px-5 py-4 text-center"><Badge size="sm" color={item.soDaNop >= item.soDoiTuong && item.soDoiTuong > 0 ? "success" : "warning"}>{item.soDaNop}/{item.soDoiTuong} đơn vị đã nộp</Badge></td><td className="px-5 py-4 text-center"><button type="button" onClick={() => navigate(`/khao-sat-thi-hanh-phap-luat/cuoc-khao-sat/${item.id}`)} className="rounded-lg px-3 py-2 text-xs font-medium text-brand-500 hover:bg-brand-50">Xem chi tiết</button></td></tr>)}</tbody></table></div></div></div>;
}
