import { useEffect, useState } from "react";
import { useNavigate } from "react-router";
import Alert from "../../../app/components/ui/alert/Alert";
import Badge from "../../../app/components/ui/badge/Badge";
import Label from "../../../app/components/forms/Label";
import Select from "../../../app/components/forms/Select";
import { getCuocKhaoSats, getDashboardKhaoSat } from "../api/khaoSatThiHanhPhapLuatApi";

const errorMessage = (error) => error?.response?.data?.message || error?.response?.data || error?.message || "Không thể tải dashboard khảo sát.";

export default function DashboardKhaoSatPage() {
  const navigate = useNavigate(); const [surveys, setSurveys] = useState([]); const [surveyId, setSurveyId] = useState(""); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { try { setLoading(true); const result = await getCuocKhaoSats({ pageSize: 100 }); setSurveys(result.items || []); } catch (requestError) { setError(errorMessage(requestError)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const choose = async (id) => { setSurveyId(id); setData(null); if (!id) return; try { setLoading(true); setError(""); setData(await getDashboardKhaoSat(id)); } catch (requestError) { setError(errorMessage(requestError)); } finally { setLoading(false); } };
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Dashboard khảo sát</h1><p className="mt-1 text-sm text-gray-500">Theo dõi tiến độ nộp kết quả, lỗi dữ liệu và báo cáo của từng cuộc khảo sát.</p></div>{surveyId && <button type="button" onClick={() => navigate(`/khao-sat-thi-hanh-phap-luat/bao-cao?cuocKhaoSatId=${surveyId}`)} className="rounded-lg bg-brand-500 px-4 py-2 text-sm font-medium text-white">Báo cáo khảo sát</button>}</div>{error && <Alert variant="error" title="Có lỗi" message={error} />}<div className="max-w-2xl rounded-xl border bg-white p-5 dark:border-white/[0.05] dark:bg-white/[0.03]"><Label>Cuộc khảo sát</Label><Select value={surveyId} options={[{ value: "", label: "Chọn cuộc khảo sát" }, ...surveys.map((item) => ({ value: item.id, label: `${item.maCuocKhaoSat} · ${item.tenCuocKhaoSat}` }))]} onChange={choose} /></div>{loading && <div className="py-10 text-center text-sm text-gray-500">Đang tải dữ liệu...</div>}{data && <><div className="grid gap-4 sm:grid-cols-4"><Metric label="Nhóm đối tượng" value={data.tongNhom} /><Metric label="Nhóm đã nhập kết quả" value={data.soNhomDaNhapKetQua} /><Metric label="Tổng file kết quả" value={data.soFileKetQua} /><Metric label="File phiên bản mới nhất" value={data.soFileMoiNhat} /></div><div className="overflow-hidden rounded-xl border bg-white dark:border-white/[0.05] dark:bg-white/[0.03]"><div className="border-b px-5 py-4"><h2 className="font-semibold">Tiến độ theo nhóm đối tượng</h2></div><div className="max-w-full overflow-x-auto"><table className="w-full"><thead><tr className="border-b"><th className="px-5 py-3 text-left text-xs text-gray-500">Nhóm</th><th className="px-5 py-3 text-center text-xs text-gray-500">Kết quả</th><th className="px-5 py-3 text-center text-xs text-gray-500">Số lần upload</th></tr></thead><tbody className="divide-y">{data.nhomDoiTuong?.map((item) => <tr key={item.id}><td className="px-5 py-4"><div className="font-medium">{item.tenNhom}</div><div className="text-xs text-gray-500">{item.maNhom}</div></td><td className="px-5 py-4 text-center"><Badge size="sm" color={item.daNhapKetQua ? "success" : "light"}>{item.daNhapKetQua ? "Đã nhập" : "Chưa nhập"}</Badge></td><td className="px-5 py-4 text-center text-sm">{item.soLanUpload}</td></tr>)}</tbody></table></div></div></>}</div>;
}
function Metric({ label, value }) { return <div className="rounded-xl border bg-white p-5 dark:border-white/[0.05] dark:bg-white/[0.03]"><div className="text-sm text-gray-500">{label}</div><div className="mt-2 text-2xl font-semibold text-gray-800 dark:text-white/90">{value ?? 0}</div></div>; }
