// <auto-generated />
using System;
using DanhMucService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DanhMucService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DanhMucDbContext))]
    [Migration("20260930075250_InitDanhMucSchema")]
    partial class InitDanhMucSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dm")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucBuocQuyTrinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit");

                    b.Property<string>("CachHoanThanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChoPhepBoQua")
                        .HasColumnType("bit");

                    b.Property<bool>("ChoPhepQuayLui")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonViTiepNhanMacDinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLanTraLaiToiDa")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongPhanHoiToiThieu")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayCanhBaoSapHan")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayXuLyTieuChuan")
                        .HasColumnType("int");

                    b.Property<string>("TenBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("YeuCauFileDinhKem")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DonViTiepNhanMacDinhId");

                    b.HasIndex("QuyTrinhSoanThaoId");

                    b.ToTable("DanhMucBuocQuyTrinhs", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucCanBo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DonViQuanLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiLaoDong")
                        .HasColumnType("int");

                    b.Property<decimal?>("MucPhiBaoHiemTrachNhiem")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime?>("NgayKyHopDongLaoDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhBoNhiem")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhCapThe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayQuyetDinhDung")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTuyenDung")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PhongBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoHopDongLaoDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhBoNhiem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhCapThe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoQuyetDinhDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoTheCongChungVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTienBHXH")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("SoTienBHYT")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("TenCanBo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrinhDoChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ViTriViecLam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViQuanLyId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("DanhMucCanBos", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucChuyenBuocQuyTrinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DenBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DieuKienKetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsKetThuc")
                        .HasColumnType("bit");

                    b.Property<bool>("LaNhanhMacDinh")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiChuyenBuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TuBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("YeuCauNhapLyDo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DenBuocId");

                    b.HasIndex("QuyTrinhSoanThaoId");

                    b.HasIndex("TuBuocId");

                    b.ToTable("DanhMucChuyenBuocQuyTrinhs", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucDiaDanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DiaDanhCapTrenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("STTSapXep")
                        .HasColumnType("int");

                    b.Property<string>("TenDiaDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucDiaDanhs", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucDonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucDanhQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonViChuQuanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoVaTenNguoiQuanLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MaQHNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoaiDonVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("STTSapXep")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TinhNangThanhToan")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucDonVis", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucLinhVuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLinhVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLinhVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucLinhVucs", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucPhongBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DanhMucDonViId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LoaiPhongBan")
                        .HasColumnType("int");

                    b.Property<string>("MaPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucDonViId");

                    b.ToTable("DanhMucPhongBans", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucQuyTrinhSoanThao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapApDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DanhMucVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DanhMucVanBanIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiQuyTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaQuyTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhienBan")
                        .HasColumnType("int");

                    b.Property<string>("TenQuyTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucVanBanId");

                    b.ToTable("DanhMucQuyTrinhSoanThaos", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucTieuChiDiem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiemToiDa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViGiaTri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KieuGiaTri")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiTieuChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaTieuChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTieuChi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucTieuChiDiems", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucTieuChiDiemMuc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BaoGomDenGiaTri")
                        .HasColumnType("bit");

                    b.Property<bool>("BaoGomTuGiaTri")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DanhMucTieuChiDiemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DenGiaTri")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Diem")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhanHienThi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TuGiaTri")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucTieuChiDiemMucs", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucTrangThai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaMauHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucTrangThais", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucVanBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapChinhQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuTheBanHanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyHieuMau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoaiVanBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DanhMucVanBans", "dm");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.HoSoVanBanUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuocHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("HoSoVanBans", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucBuocQuyTrinh", b =>
                {
                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucDonVi", null)
                        .WithMany()
                        .HasForeignKey("DonViTiepNhanMacDinhId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucQuyTrinhSoanThao", null)
                        .WithMany()
                        .HasForeignKey("QuyTrinhSoanThaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucCanBo", b =>
                {
                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucDonVi", "DonViQuanLy")
                        .WithMany()
                        .HasForeignKey("DonViQuanLyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucPhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonViQuanLy");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucChuyenBuocQuyTrinh", b =>
                {
                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("DenBuocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucQuyTrinhSoanThao", null)
                        .WithMany()
                        .HasForeignKey("QuyTrinhSoanThaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucBuocQuyTrinh", null)
                        .WithMany()
                        .HasForeignKey("TuBuocId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucPhongBan", b =>
                {
                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucDonVi", "DanhMucDonVi")
                        .WithMany("DanhMucPhongBans")
                        .HasForeignKey("DanhMucDonViId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucDonVi");
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucQuyTrinhSoanThao", b =>
                {
                    b.HasOne("DanhMucService.Infrastructure.Persistence.Entities.DanhMucVanBan", null)
                        .WithMany()
                        .HasForeignKey("DanhMucVanBanId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DanhMucService.Infrastructure.Persistence.Entities.DanhMucDonVi", b =>
                {
                    b.Navigation("DanhMucPhongBans");
                });
#pragma warning restore 612, 618
        }
    }
}
