import { useEffect, useState } from "react";
import Alert from "../../../app/components/ui/alert/Alert";
import Badge from "../../../app/components/ui/badge/Badge";
import Input from "../../../app/components/forms/input/InputField";
import Label from "../../../app/components/forms/Label";
import Select from "../../../app/components/forms/Select";
import { Modal } from "../../../app/components/ui/modal";
import { createQuyTrinh, deleteQuyTrinh, getQuyTrinhs, updateQuyTrinh } from "../api/quyTrinhSoanThaoApi";

const newStep = (order = 1) => ({ maBuoc: `BUOC_${order}`, tenBuoc: "", thuTuSapXep: order, loaiBuoc: "XuLy", batBuoc: true, choPhepBoQua: false, choPhepQuayLui: false, yeuCauFileDinhKem: false, soLanTraLaiToiDa: 0 });
const emptyForm = () => ({ id: "", maQuyTrinh: "", tenQuyTrinh: "", loaiQuyTrinh: "XayDung", capApDung: "", phienBan: 1, trangThai: true, moTa: "", ghiChu: "", buocQuyTrinhs: [newStep()] , chuyenBuocs: [] });
const errorMessage = (error) => error?.response?.data?.message || error?.message || "Không thể xử lý yêu cầu.";

export default function QuyTrinhSoanThaoPage() {
  const [items, setItems] = useState([]); const [search, setSearch] = useState(""); const [pageSize, setPageSize] = useState(10); const [pageCurrent, setPageCurrent] = useState(1); const [totalCount, setTotalCount] = useState(0);
  const [loading, setLoading] = useState(false); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [form, setForm] = useState(emptyForm()); const [open, setOpen] = useState(false);
  const load = async () => { try { setLoading(true); setError(""); const response = await getQuyTrinhs({ search, pageSize, pageCurrent }); setItems(response.data || []); setTotalCount(response.totalCount || 0); } catch (e) { setError(errorMessage(e)); } finally { setLoading(false); } };
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [search, pageSize, pageCurrent]);
  const updateStep = (index, key, value) => setForm((current) => ({ ...current, buocQuyTrinhs: current.buocQuyTrinhs.map((step, i) => i === index ? { ...step, [key]: value } : step) }));
  const addStep = () => setForm((current) => ({ ...current, buocQuyTrinhs: [...current.buocQuyTrinhs, newStep(current.buocQuyTrinhs.length + 1)] }));
  const edit = (item) => { setForm({ ...emptyForm(), ...item, buocQuyTrinhs: (item.buocQuyTrinhs || []).map((step, index) => ({ ...newStep(index + 1), ...step })) || [newStep()], chuyenBuocs: item.chuyenBuocs || [] }); setOpen(true); };
  const submit = async (event) => { event.preventDefault(); if (!form.maQuyTrinh.trim() || !form.tenQuyTrinh.trim()) { setError("Vui lòng nhập mã và tên quy trình."); return; } if (!form.buocQuyTrinhs.length || form.buocQuyTrinhs.some((x) => !x.maBuoc.trim() || !x.tenBuoc.trim())) { setError("Mỗi bước phải có mã và tên."); return; } try { setSubmitting(true); setError(""); const payload = { ...form, phienBan: Number(form.phienBan), buocQuyTrinhs: form.buocQuyTrinhs.map((step, index) => ({ ...step, thuTuSapXep: Number(step.thuTuSapXep) || index + 1, soLanTraLaiToiDa: Number(step.soLanTraLaiToiDa) || 0 })) }; if (form.id) await updateQuyTrinh(form.id, payload); else await createQuyTrinh(payload); setSuccess(form.id ? "Cập nhật quy trình thành công." : "Thêm quy trình thành công."); setOpen(false); load(); } catch (e) { setError(errorMessage(e)); } finally { setSubmitting(false); } };
  const remove = async (item) => { if (!window.confirm(`Xóa quy trình "${item.tenQuyTrinh}"?`)) return; try { await deleteQuyTrinh(item.id); setSuccess("Xóa quy trình thành công."); load(); } catch (e) { setError(errorMessage(e)); } };
  const totalPages = Math.max(1, Math.ceil(totalCount / pageSize));
  return <div className="space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-semibold text-gray-800 dark:text-white/90">Quy trình soạn thảo</h1><p className="mt-1 text-sm text-gray-500 dark:text-gray-400">Thiết lập quy trình, bước xử lý và trạng thái áp dụng.</p></div><button type="button" onClick={() => { setForm(emptyForm()); setOpen(true); }} className="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white hover:bg-brand-600">+ Thêm quy trình</button></div>
    {error && <Alert variant="error" title="Không thể xử lý" message={error} />}{success && <Alert variant="success" title="Hoàn tất" message={success} />}
    <div className="overflow-hidden rounded-xl border border-gray-200 bg-white dark:border-white/[0.03] dark:border-white/[0.05]"><div className="grid gap-4 border-b border-gray-100 p-5 sm:grid-cols-4 dark:border-white/[0.05]"><div><Label>Hiển thị</Label><Select value={pageSize} onChange={(value) => { setPageSize(Number(value)); setPageCurrent(1); }} options={[5,10,20,50].map((value) => ({ value, label: `${value} thông tin` }))} /></div><div className="sm:col-span-3"><Label>Tìm kiếm</Label><Input value={search} onChange={(e) => { setSearch(e.target.value); setPageCurrent(1); }} placeholder="Tìm theo mã, tên hoặc mô tả quy trình..." /></div></div>
      <div className="max-w-full overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-gray-100 dark:border-white/[0.05]"><th className="px-5 py-3 text-left text-xs font-medium text-gray-500">Quy trình</th><th className="px-5 py-3 text-left text-xs font-medium text-gray-500">Loại / cấp áp dụng</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Bước / nhánh</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Trạng thái</th><th className="px-5 py-3 text-center text-xs font-medium text-gray-500">Thao tác</th></tr></thead><tbody className="divide-y divide-gray-100 dark:divide-white/[0.05]">{loading ? <tr><td colSpan="5" className="px-5 py-10 text-center text-sm text-gray-500">Đang tải dữ liệu...</td></tr> : items.length ? items.map((item) => <tr key={item.id} className="hover:bg-gray-50 dark:hover:bg-white/[0.02]"><td className="px-5 py-4"><div className="font-medium text-gray-800 dark:text-white/90">{item.tenQuyTrinh}</div><div className="mt-1 text-xs text-gray-500">{item.maQuyTrinh} · Phiên bản {item.phienBan}</div></td><td className="px-5 py-4 text-sm text-gray-600 dark:text-gray-300"><div>{item.tenLoaiQuyTrinh || item.loaiQuyTrinh}</div><div className="mt-1 text-xs text-gray-500">{item.capApDung || "Chưa xác định"}</div></td><td className="px-5 py-4 text-center text-sm text-gray-600 dark:text-gray-300">{item.soBuoc ?? item.buocQuyTrinhs?.length ?? 0} / {item.soNhanhChuyen ?? item.chuyenBuocs?.length ?? 0}</td><td className="px-5 py-4 text-center"><Badge size="sm" color={item.trangThai ? "success" : "light"}>{item.trangThai ? "Đang dùng" : "Tạm dừng"}</Badge></td><td className="px-5 py-4"><div className="flex justify-center gap-1"><button onClick={() => edit(item)} className="rounded-lg px-3 py-2 text-xs font-medium text-gray-600 hover:bg-gray-100 hover:text-brand-500">Sửa</button><button onClick={() => remove(item)} className="rounded-lg px-3 py-2 text-xs font-medium text-gray-600 hover:bg-gray-100 hover:text-error-500">Xóa</button></div></td></tr>) : <tr><td colSpan="5" className="px-5 py-10 text-center text-sm text-gray-500">Không có dữ liệu quy trình.</td></tr>}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-gray-100 px-5 py-4 text-sm text-gray-500 dark:border-white/[0.05]"><span>{totalCount} quy trình</span><div className="flex gap-2"><button disabled={pageCurrent === 1 || loading} onClick={() => setPageCurrent((x) => x - 1)} className="rounded-lg border px-3 py-2 disabled:opacity-50">Trước</button><span className="px-3 py-2">{pageCurrent}/{totalPages}</span><button disabled={pageCurrent >= totalPages || loading} onClick={() => setPageCurrent((x) => x + 1)} className="rounded-lg border px-3 py-2 disabled:opacity-50">Sau</button></div></div></div>
    <Modal isOpen={open} onClose={() => !submitting && setOpen(false)} className="max-w-5xl p-6"><form onSubmit={submit} className="space-y-5"><h4 className="text-lg font-semibold text-gray-800 dark:text-white/90">{form.id ? "Cập nhật quy trình" : "Thêm mới quy trình"}</h4><div className="grid gap-4 sm:grid-cols-2"><div><Label>Mã quy trình *</Label><Input value={form.maQuyTrinh} onChange={(e) => setForm({...form, maQuyTrinh:e.target.value})} disabled={submitting} /></div><div><Label>Tên quy trình *</Label><Input value={form.tenQuyTrinh} onChange={(e) => setForm({...form, tenQuyTrinh:e.target.value})} disabled={submitting} /></div><div><Label>Loại quy trình</Label><Select value={form.loaiQuyTrinh} onChange={(value) => setForm({...form, loaiQuyTrinh:value})} options={[{value:"XayDung",label:"Xây dựng văn bản"},{value:"SoanThao",label:"Soạn thảo"}]} /></div><div><Label>Cấp áp dụng</Label><Input value={form.capApDung || ""} onChange={(e) => setForm({...form, capApDung:e.target.value})} placeholder="Ví dụ: Cấp tỉnh" /></div></div><div><Label>Mô tả</Label><Input value={form.moTa || ""} onChange={(e) => setForm({...form, moTa:e.target.value})} /></div>
      <div className="rounded-xl border border-gray-200 p-4 dark:border-white/[0.08]"><div className="mb-4 flex items-center justify-between"><div><h5 className="font-medium text-gray-800 dark:text-white/90">Các bước xử lý</h5><p className="text-xs text-gray-500">Khai báo các bước theo thứ tự của quy trình.</p></div><button type="button" onClick={addStep} className="rounded-lg border border-brand-200 px-3 py-2 text-sm font-medium text-brand-500 hover:bg-brand-50">+ Thêm bước</button></div><div className="space-y-3">{form.buocQuyTrinhs.map((step, index) => <div key={index} className="grid items-end gap-3 rounded-lg bg-gray-50 p-3 sm:grid-cols-12 dark:bg-white/[0.04]"><div className="sm:col-span-2"><Label>Thứ tự</Label><Input type="number" min="1" value={step.thuTuSapXep} onChange={(e) => updateStep(index,"thuTuSapXep",e.target.value)} /></div><div className="sm:col-span-3"><Label>Mã bước *</Label><Input value={step.maBuoc} onChange={(e) => updateStep(index,"maBuoc",e.target.value)} /></div><div className="sm:col-span-5"><Label>Tên bước *</Label><Input value={step.tenBuoc} onChange={(e) => updateStep(index,"tenBuoc",e.target.value)} /></div><div className="sm:col-span-2"><button type="button" disabled={form.buocQuyTrinhs.length === 1} onClick={() => setForm({...form, buocQuyTrinhs:form.buocQuyTrinhs.filter((_,i) => i !== index)})} className="w-full rounded-lg px-3 py-2 text-sm text-error-500 hover:bg-error-50 disabled:opacity-40">Xóa bước</button></div></div>)}</div></div><label className="flex items-center gap-2 text-sm text-gray-700 dark:text-gray-300"><input type="checkbox" checked={form.trangThai} onChange={(e) => setForm({...form, trangThai:e.target.checked})} /> Đang áp dụng</label><div className="flex justify-end gap-3 border-t border-gray-100 pt-5 dark:border-white/[0.05]"><button type="button" onClick={() => setOpen(false)} className="rounded-lg border px-4 py-2.5 text-sm font-medium">Hủy</button><button disabled={submitting} className="rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{submitting ? "Đang lưu..." : "Lưu quy trình"}</button></div></form></Modal></div>;
}
