using System.IO.Compression;
using System.Net;
using System.Xml.Linq;
using BuildingBlocks.Abstractions;
using Microsoft.EntityFrameworkCore;
using XayDungVanBanService.Application.Abstractions;
using XayDungVanBanService.Application.DTOs;
using XayDungVanBanService.Infrastructure.Persistence;
using XayDungVanBanService.Infrastructure.Persistence.Entities;

namespace XayDungVanBanService.Application.Services;

public sealed class XayDungVanBanThamDinhService(XayDungVanBanDbContext db, ICurrentUserContext user, IWebHostEnvironment env) : IXayDungVanBanThamDinhService
{
 public async Task<XayDungVanBanThamDinhDto> CreateAsync(TaoHoSoThamDinhRequest r,CancellationToken ct=default){var a=Actor(); var source=await db.BoHoSoNghiepVus.OrderByDescending(x=>x.CreatedAt).FirstOrDefaultAsync(x=>x.HoSoXayDungVanBanId==r.HoSoId&&x.LoaiBoHoSo==LoaiBoHoSo.TrinhThamDinh&&x.TrangThai==TrangThaiBoHoSo.DaGui&&!x.IsDeleted,ct)??throw new InvalidOperationException("Chưa có hồ sơ trình thẩm định đã gửi."); if(await Data(r.HoSoId,true,ct)!=null)throw new InvalidOperationException("Đã có hồ sơ thẩm định."); await using var tx=await db.Database.BeginTransactionAsync(ct); var b=new BoHoSoNghiepVu{HoSoXayDungVanBanId=r.HoSoId,BuocQuyTrinhId=source.BuocQuyTrinhId,LoaiBoHoSo=LoaiBoHoSo.ThamDinh,TrangThai=TrangThaiBoHoSo.Nhap,LanXuLy=await Next(r.HoSoId,source.BuocQuyTrinhId,ct),BoHoSoNguonId=source.Id,NguoiLapId=a.U,DonViLapId=a.D,CreatedBy=a.U.ToString()}; db.BoHoSoNghiepVus.Add(b); var d=new HoSoXayDungVanBanThamDinh{BoHoSoNghiepVuId=b.Id};db.HoSoXayDungVanBanThamDinhs.Add(d);var links=await db.BoHoSoNghiepVuTaiLieus.Where(x=>x.BoHoSoNghiepVuId==source.Id&&!x.IsDeleted).ToListAsync(ct);foreach(var x in links)db.BoHoSoNghiepVuTaiLieus.Add(new(){BoHoSoNghiepVuId=b.Id,HoSoXayDungVanBanFileId=x.HoSoXayDungVanBanFileId,LoaiTaiLieuId=x.LoaiTaiLieuId,HinhThucThem="KeThua",BoHoSoTaiLieuNguonId=x.Id,ThuTu=x.ThuTu,CreatedBy=a.U.ToString()});Log(r.HoSoId,b.Id,"TAO_HO_SO_THAM_DINH","Tạo hồ sơ thẩm định",a);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Dto(r.HoSoId,b,d);}
 public async Task<XayDungVanBanThamDinhDto?> GetAsync(Guid id,CancellationToken ct=default){var x=await Data(id,false,ct);return x==null?null:Dto(id,x.B,x.D);}
 public async Task<XayDungVanBanThamDinhDto?> TiepNhanAsync(Guid id,TiepNhanThamDinhRequest r,CancellationToken ct=default){var a=Actor();var x=await Data(id,true,ct);if(x==null)return null;Nhap(x.B);x.B.TrangThai=TrangThaiBoHoSo.DaTiepNhan;x.D.NgayTiepNhan=r.NgayTiepNhan??DateTime.UtcNow;Log(id,x.B.Id,"TIEP_NHAN_THAM_DINH","Tiếp nhận hồ sơ thẩm định",a);await db.SaveChangesAsync(ct);return Dto(id,x.B,x.D);}
 public async Task<XayDungVanBanThamDinhDto?> CapNhatKetQuaAsync(Guid id,CapNhatKetQuaThamDinhRequest r,CancellationToken ct=default){var a=Actor();var x=await Data(id,true,ct);if(x==null)return null;TiepNhan(x.B);x.D.HinhThucThamDinh=r.HinhThucThamDinh;x.D.NgayThamDinh=r.NgayThamDinh;x.D.KetQuaThamDinh=r.KetQuaThamDinh;x.D.NoiDungKetLuan=r.NoiDungKetLuan;x.D.NguoiKetLuanId=r.NguoiKetLuanId;Log(id,x.B.Id,"CAP_NHAT_KET_QUA_THAM_DINH","Cập nhật kết quả thẩm định",a);await db.SaveChangesAsync(ct);return Dto(id,x.B,x.D);}
 public async Task<IReadOnlyList<XayDungVanBanTaiLieuDto>?> GetTaiLieuAsync(Guid id,CancellationToken ct=default){var x=await Data(id,false,ct);if(x==null)return null;return await(from l in db.BoHoSoNghiepVuTaiLieus join f in db.HoSoXayDungVanBanFiles on l.HoSoXayDungVanBanFileId equals f.Id where l.BoHoSoNghiepVuId==x.B.Id&&!l.IsDeleted&&!f.IsDeleted select FD(f)).ToListAsync(ct);}
 public async Task<XayDungVanBanTaiLieuDto?> UploadTaiLieuAsync(Guid id,TaiTaiLieuThamDinhRequest r,CancellationToken ct=default){var a=Actor();var x=await Data(id,true,ct);if(x==null)return null;TiepNhan(x.B);if(r.LoaiTaiLieuId==Guid.Empty||r.NoiDung.Length==0)throw new InvalidOperationException("Thiếu tài liệu.");var name=Path.GetFileName(r.TenFile);var dir=Path.Combine(env.ContentRootPath,"uploads","xay-dung-van-ban",id.ToString("N"));Directory.CreateDirectory(dir);var store=$"{Guid.NewGuid():N}_{name}";var path=Path.Combine(dir,store);await using(var o=File.Create(path))await r.NoiDung.CopyToAsync(o,ct);try{var old=await db.HoSoXayDungVanBanFiles.Where(item=>item.HoSoXayDungVanBanId==id&&item.LoaiTaiLieuId==r.LoaiTaiLieuId&&!item.IsDeleted).ToListAsync(ct);foreach(var previous in old.Where(item=>item.IsCurrent))previous.IsCurrent=false;var uploadedFile=new HoSoXayDungVanBanFile{HoSoXayDungVanBanId=id,LoaiTaiLieuId=r.LoaiTaiLieuId,TenTaiLieu=r.TenTaiLieu,TenFile=name,DuongDanFile=Path.Combine("uploads","xay-dung-van-ban",id.ToString("N"),store).Replace('\\','/'),MimeType=r.MimeType,DungLuong=r.NoiDung.Length,PhienBan=old.Count==0?1:old.Max(z=>z.PhienBan)+1,NguoiTaiLenId=a.U,CreatedBy=a.U.ToString()};db.HoSoXayDungVanBanFiles.Add(uploadedFile);db.BoHoSoNghiepVuTaiLieus.Add(new(){BoHoSoNghiepVuId=x.B.Id,HoSoXayDungVanBanFileId=uploadedFile.Id,LoaiTaiLieuId=uploadedFile.LoaiTaiLieuId,HinhThucThem="TaoMoi",CreatedBy=a.U.ToString()});Log(id,x.B.Id,"TAI_TAI_LIEU_THAM_DINH",$"Tải tài liệu {r.TenTaiLieu}",a,uploadedFile.Id);await db.SaveChangesAsync(ct);return FD(uploadedFile);}catch{if(File.Exists(path))File.Delete(path);throw;}}
 public async Task<bool> DeleteTaiLieuAsync(Guid id,Guid lid,CancellationToken ct=default){var a=Actor();var x=await Data(id,true,ct);if(x==null)return false;TiepNhan(x.B);var l=await db.BoHoSoNghiepVuTaiLieus.FirstOrDefaultAsync(z=>z.Id==lid&&z.BoHoSoNghiepVuId==x.B.Id&&!z.IsDeleted,ct);if(l==null)return false;if(l.HinhThucThem=="KeThua")throw new InvalidOperationException("Không thể gỡ tài liệu kế thừa.");l.IsDeleted=true;Log(id,x.B.Id,"GO_TAI_LIEU_THAM_DINH","Gỡ tài liệu",a,l.HoSoXayDungVanBanFileId);await db.SaveChangesAsync(ct);return true;}
 public async Task<DieuKienGuiKetQuaThamDinhDto?> KiemTraAsync(Guid id,CancellationToken ct=default){var x=await Data(id,false,ct);if(x==null)return null;var c=await Conditions(x,ct);return new(c.Count==0,c);}
 public async Task<XayDungVanBanThamDinhDto?> YeuCauBoSungAsync(Guid id,YeuCauBoSungThamDinhRequest r,CancellationToken ct=default){var a=Actor();if(r.BuocQuyTrinhSoanThaoId==Guid.Empty||r.TrangThaiHoSoBoSungId==Guid.Empty||string.IsNullOrWhiteSpace(r.NoiDungYeuCauBoSung))throw new InvalidOperationException("Thiếu thông tin yêu cầu bổ sung.");var x=await Data(id,true,ct);if(x==null)return null;TiepNhan(x.B);x.D.NoiDungYeuCauBoSung=r.NoiDungYeuCauBoSung;x.D.HanBoSung=r.HanBoSung;await Move(id,x,a,r.BuocQuyTrinhSoanThaoId,r.TrangThaiHoSoBoSungId,"YEU_CAU_BO_SUNG",r.NoiDungYeuCauBoSung,ct);return Dto(id,x.B,x.D);}
 public async Task<XayDungVanBanThamDinhDto?> GuiKetQuaAsync(Guid id,GuiKetQuaThamDinhRequest r,CancellationToken ct=default){var a=Actor();var x=await Data(id,true,ct);if(x==null)return null;var c=await Conditions(x,ct);if(c.Count>0)throw new InvalidOperationException(string.Join(" ",c));x.D.NgayGuiKetQua=r.NgayGuiKetQua??DateTime.UtcNow;await Move(id,x,a,r.BuocQuyTrinhTiepTheoId,r.TrangThaiHoSoTiepTheoId,"GUI_KET_QUA_THAM_DINH","Gửi kết quả thẩm định",ct);return Dto(id,x.B,x.D);}
 public async Task<bool> HuyAsync(Guid id,CancellationToken ct=default){var a=Actor();var x=await Data(id,true,ct);if(x==null)return false;Nhap(x.B);x.B.IsDeleted=true;Log(id,x.B.Id,"HUY_THAM_DINH","Hủy hồ sơ thẩm định",a);await db.SaveChangesAsync(ct);return true;}
 public async Task<KetQuaSoSanhDuThaoDto?> SoSanhAsync(Guid id,SoSanhDuThaoRequest r,CancellationToken ct=default){var a=Actor();var fs=await db.HoSoXayDungVanBanFiles.Where(f=>f.HoSoXayDungVanBanId==id&&(f.Id==r.FileGocId||f.Id==r.FileSoSanhId)&&!f.IsDeleted).ToListAsync(ct);if(fs.Count!=2)throw new InvalidOperationException("Hai file phải thuộc cùng hồ sơ.");var p1=Path.Combine(env.ContentRootPath,fs.Single(f=>f.Id==r.FileGocId).DuongDanFile);var p2=Path.Combine(env.ContentRootPath,fs.Single(f=>f.Id==r.FileSoSanhId).DuongDanFile);var s1=ReadDocx(p1);var s2=ReadDocx(p2);var old=s1.Split('\n',StringSplitOptions.RemoveEmptyEntries);var now=s2.Split('\n',StringSplitOptions.RemoveEmptyEntries);var add=now.Count(z=>!old.Contains(z));var del=old.Count(z=>!now.Contains(z));var e=new HoSoXayDungVanBanSoSanhDuThao{HoSoXayDungVanBanId=id,FileGocId=r.FileGocId,FileSoSanhId=r.FileSoSanhId,SoNoiDungThem=add,SoNoiDungXoa=del,SoNoiDungSua=Math.Min(add,del),NoiDungSoSanhHtml=$"<pre class=\"removed\">{WebUtility.HtmlEncode(s1)}</pre><pre class=\"added\">{WebUtility.HtmlEncode(s2)}</pre>",CreatedBy=a.U.ToString()};db.HoSoXayDungVanBanSoSanhDuThaos.Add(e);await db.SaveChangesAsync(ct);return SD(e);}
 public async Task<KetQuaSoSanhDuThaoDto?> GetSoSanhAsync(Guid h,Guid id,CancellationToken ct=default){var e=await db.HoSoXayDungVanBanSoSanhDuThaos.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id&&x.HoSoXayDungVanBanId==h&&!x.IsDeleted,ct);return e==null?null:SD(e);}
 private async Task Move(Guid id,ThamDinhData x,A a,Guid b,Guid s,string action,string msg,CancellationToken ct){if(b==Guid.Empty||s==Guid.Empty)throw new InvalidOperationException("Thiếu bước hoặc trạng thái.");await using var tx=await db.Database.BeginTransactionAsync(ct);x.B.TrangThai=TrangThaiBoHoSo.DaHoanThanh;x.B.NgayHoanThanh=DateTime.UtcNow;var h=await db.HoSoXayDungVanBans.FirstAsync(z=>z.Id==id,ct);var pb=h.BuocHienTaiId;var ps=h.TrangThaiHoSoId;h.BuocHienTaiId=b;h.TrangThaiHoSoId=s;Log(id,x.B.Id,action,msg,a,null,pb,b,ps,s);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);}
 private async Task<List<string>> Conditions(ThamDinhData x,CancellationToken ct){var c=new List<string>();if(string.IsNullOrWhiteSpace(x.D.KetQuaThamDinh))c.Add("Chưa có kết quả thẩm định.");if(string.IsNullOrWhiteSpace(x.D.NoiDungKetLuan))c.Add("Chưa có kết luận thẩm định.");if(!await db.BoHoSoNghiepVuTaiLieus.AnyAsync(z=>z.BoHoSoNghiepVuId==x.B.Id&&!z.IsDeleted,ct))c.Add("Chưa có tài liệu.");return c;}
 private async Task<ThamDinhData?> Data(Guid id,bool t,CancellationToken ct){var b=t?db.BoHoSoNghiepVus:db.BoHoSoNghiepVus.AsNoTracking();var d=t?db.HoSoXayDungVanBanThamDinhs:db.HoSoXayDungVanBanThamDinhs.AsNoTracking();return await(from x in b join y in d on x.Id equals y.BoHoSoNghiepVuId where x.HoSoXayDungVanBanId==id&&x.LoaiBoHoSo==LoaiBoHoSo.ThamDinh&&!x.IsDeleted orderby x.CreatedAt descending select new ThamDinhData(x,y)).FirstOrDefaultAsync(ct);}
 private async Task<int> Next(Guid h,Guid b,CancellationToken ct)=>(await db.BoHoSoNghiepVus.Where(x=>x.HoSoXayDungVanBanId==h&&x.BuocQuyTrinhId==b).Select(x=>(int?)x.LanXuLy).MaxAsync(ct)??0)+1; private static void Nhap(BoHoSoNghiepVu b){if(b.TrangThai!=TrangThaiBoHoSo.Nhap)throw new InvalidOperationException("Hồ sơ không ở trạng thái nhập.");} private static void TiepNhan(BoHoSoNghiepVu b){if(b.TrangThai!=TrangThaiBoHoSo.DaTiepNhan)throw new InvalidOperationException("Hồ sơ chưa được tiếp nhận.");}
 private A Actor(){if(!user.IsAuthenticated||user.UserId is not Guid u||user.DonViId is not Guid d)throw new UnauthorizedAccessException();return new(u,d);} private void Log(Guid h,Guid b,string ac,string n,A a,Guid? f=null,Guid? pb=null,Guid? nb=null,Guid? ps=null,Guid? ns=null)=>db.HoSoXayDungVanBanLichSuXuLys.Add(new(){HoSoXayDungVanBanId=h,BoHoSoNghiepVuId=b,HanhDong=ac,NoiDung=n,NguoiXuLyId=a.U,DonViXuLyId=a.D,HoSoXayDungVanBanFileId=f,BuocQuyTrinhTruocId=pb,BuocQuyTrinhSauId=nb,TrangThaiTruocId=ps,TrangThaiSauId=ns,CreatedBy=a.U.ToString()});
 private static string ReadDocx(string p){using var z=ZipFile.OpenRead(p);var e=z.GetEntry("word/document.xml")??throw new InvalidOperationException("File không phải DOCX hợp lệ.");using var s=e.Open();var x=XDocument.Load(s);return string.Join('\n',x.Descendants().Where(n=>n.Name.LocalName=="p").Select(n=>string.Concat(n.Descendants().Where(t=>t.Name.LocalName=="t").Select(t=>t.Value))));} private static XayDungVanBanThamDinhDto Dto(Guid h,BoHoSoNghiepVu b,HoSoXayDungVanBanThamDinh d)=>new(h,b.Id,b.TrangThai.ToString(),d.NgayTiepNhan,d.HinhThucThamDinh,d.NgayThamDinh,d.KetQuaThamDinh,d.NoiDungKetLuan,d.NoiDungYeuCauBoSung,d.HanBoSung,d.NguoiKetLuanId); private static XayDungVanBanTaiLieuDto FD(HoSoXayDungVanBanFile f)=>new(f.Id,f.LoaiTaiLieuId,f.TenTaiLieu,f.PhienBan,f.TenFile,f.DuongDanFile,f.MimeType,f.DungLuong,f.IsCurrent,f.NgayTaiLen);private static KetQuaSoSanhDuThaoDto SD(HoSoXayDungVanBanSoSanhDuThao e)=>new(e.Id,e.HoSoXayDungVanBanId,e.FileGocId,e.FileSoSanhId,e.SoNoiDungThem,e.SoNoiDungXoa,e.SoNoiDungSua,e.NoiDungSoSanhHtml,e.CreatedAt);private sealed record ThamDinhData(BoHoSoNghiepVu B,HoSoXayDungVanBanThamDinh D);private sealed record A(Guid U,Guid D);
}
