using BuildingBlocks.Abstractions;
using Microsoft.EntityFrameworkCore;
using XayDungVanBanService.Application.Abstractions;
using XayDungVanBanService.Application.DTOs;
using XayDungVanBanService.Infrastructure.Persistence;
using XayDungVanBanService.Infrastructure.Persistence.Entities;

namespace XayDungVanBanService.Application.Services;

public sealed class XayDungVanBanYKienUbndService(XayDungVanBanDbContext db, ICurrentUserContext user, IWebHostEnvironment environment) : IXayDungVanBanYKienUbndService
{
    public async Task<XayDungVanBanYKienUbndDto> CreateAsync(TaoHoSoYKienUbndRequest r, CancellationToken ct = default)
    {
        var actor = GetActor();
        var source = await db.BoHoSoNghiepVus.OrderByDescending(x => x.CreatedAt).FirstOrDefaultAsync(x => x.HoSoXayDungVanBanId == r.HoSoId && x.LoaiBoHoSo == LoaiBoHoSo.TrinhPheDuyet && x.TrangThai == TrangThaiBoHoSo.DaGui && !x.IsDeleted, ct) ?? throw new InvalidOperationException("Chưa có hồ sơ trình phê duyệt đã gửi.");
        if (await LoadAsync(r.HoSoId, true, ct) is not null) throw new InvalidOperationException("Đã có hồ sơ ý kiến UBND.");
        var b = new BoHoSoNghiepVu { HoSoXayDungVanBanId = r.HoSoId, BuocQuyTrinhId = source.BuocQuyTrinhId, LoaiBoHoSo = LoaiBoHoSo.YKienThanhVienUbnd, TrangThai = TrangThaiBoHoSo.Nhap, LanXuLy = 1, BoHoSoNguonId = source.Id, NguoiLapId = actor.UserId, DonViLapId = actor.DonViId, CreatedBy = actor.UserId.ToString() };
        var d = new HoSoXayDungVanBanYKienUbnd { BoHoSoNghiepVuId = b.Id }; db.BoHoSoNghiepVus.Add(b); db.HoSoXayDungVanBanYKienUbnds.Add(d);
        var links = await db.BoHoSoNghiepVuTaiLieus.Where(x => x.BoHoSoNghiepVuId == source.Id && !x.IsDeleted).ToListAsync(ct);
        foreach (var link in links) db.BoHoSoNghiepVuTaiLieus.Add(new() { BoHoSoNghiepVuId = b.Id, HoSoXayDungVanBanFileId = link.HoSoXayDungVanBanFileId, LoaiTaiLieuId = link.LoaiTaiLieuId, HinhThucThem = "KeThua", BoHoSoTaiLieuNguonId = link.Id, CreatedBy = actor.UserId.ToString() });
        await db.SaveChangesAsync(ct); return ToDto(r.HoSoId, b, d);
    }
    public async Task<XayDungVanBanYKienUbndDto?> GetAsync(Guid id, CancellationToken ct = default) { var x = await LoadAsync(id, false, ct); return x is null ? null : ToDto(id, x.B, x.D); }
    public async Task<XayDungVanBanYKienUbndDto?> UpdateAsync(Guid id, CapNhatYKienUbndRequest r, CancellationToken ct = default) { var x = await LoadAsync(id, true, ct); if (x is null) return null; EnsureNhap(x.B); var total = (r.SoDongY ?? 0) + (r.SoKhongDongY ?? 0) + (r.SoYKienKhac ?? 0); if (r.TongSoThanhVienDuocLayYKien is int t && total > t) throw new InvalidOperationException("Tổng ý kiến vượt số thành viên."); var d = x.D; d.NgayNhanYKien = r.NgayNhanYKien; d.TongSoThanhVienDuocLayYKien = r.TongSoThanhVienDuocLayYKien; d.SoDongY = r.SoDongY; d.SoKhongDongY = r.SoKhongDongY; d.SoYKienKhac = r.SoYKienKhac; d.KetLuanTongHop = r.KetLuanTongHop; d.NoiDungTongHop = r.NoiDungTongHop; d.NoiDungGiaiTrinh = r.NoiDungGiaiTrinh; await db.SaveChangesAsync(ct); return ToDto(id, x.B, d); }
    public async Task<IReadOnlyList<XayDungVanBanTaiLieuDto>?> GetTaiLieuAsync(Guid id, CancellationToken ct = default) { var x = await LoadAsync(id, false, ct); if (x is null) return null; return await (from l in db.BoHoSoNghiepVuTaiLieus join f in db.HoSoXayDungVanBanFiles on l.HoSoXayDungVanBanFileId equals f.Id where l.BoHoSoNghiepVuId == x.B.Id && !l.IsDeleted && !f.IsDeleted select FileDto(f)).ToListAsync(ct); }
    public async Task<XayDungVanBanTaiLieuDto?> UploadTaiLieuAsync(Guid id, TaiTaiLieuYKienUbndRequest r, CancellationToken ct = default) { var actor = GetActor(); var x = await LoadAsync(id, true, ct); if (x is null) return null; EnsureNhap(x.B); if (r.LoaiTaiLieuId == Guid.Empty || r.NoiDung.Length == 0) throw new InvalidOperationException("Thiếu tài liệu."); var name = Path.GetFileName(r.TenFile); var rel = Path.Combine("uploads", "xay-dung-van-ban", id.ToString("N")); var dir = Path.Combine(environment.ContentRootPath, rel); Directory.CreateDirectory(dir); var stored = $"{Guid.NewGuid():N}_{name}"; var path = Path.Combine(dir, stored); await using (var output = File.Create(path)) await r.NoiDung.CopyToAsync(output, ct); var nextVersion = (await db.HoSoXayDungVanBanFiles.Where(f => f.HoSoXayDungVanBanId == id && f.LoaiTaiLieuId == r.LoaiTaiLieuId).Select(f => (int?)f.PhienBan).MaxAsync(ct) ?? 0) + 1; var f = new HoSoXayDungVanBanFile { HoSoXayDungVanBanId = id, LoaiTaiLieuId = r.LoaiTaiLieuId, TenTaiLieu = r.TenTaiLieu, TenFile = name, DuongDanFile = Path.Combine(rel, stored).Replace('\\', '/'), MimeType = r.MimeType, DungLuong = r.NoiDung.Length, PhienBan = nextVersion, NguoiTaiLenId = actor.UserId, CreatedBy = actor.UserId.ToString() }; db.HoSoXayDungVanBanFiles.Add(f); db.BoHoSoNghiepVuTaiLieus.Add(new() { BoHoSoNghiepVuId = x.B.Id, HoSoXayDungVanBanFileId = f.Id, LoaiTaiLieuId = f.LoaiTaiLieuId, HinhThucThem = "TaoMoi", CreatedBy = actor.UserId.ToString() }); await db.SaveChangesAsync(ct); return FileDto(f); }
    public async Task<bool> DeleteTaiLieuAsync(Guid id, Guid linkId, CancellationToken ct = default) { var x = await LoadAsync(id, true, ct); if (x is null) return false; EnsureNhap(x.B); var link = await db.BoHoSoNghiepVuTaiLieus.FirstOrDefaultAsync(z => z.Id == linkId && z.BoHoSoNghiepVuId == x.B.Id && !z.IsDeleted, ct); if (link is null) return false; if (link.HinhThucThem == "KeThua") throw new InvalidOperationException("Không thể gỡ tài liệu kế thừa."); link.IsDeleted = true; await db.SaveChangesAsync(ct); return true; }
    public async Task<DieuKienGuiYKienUbndDto?> KiemTraAsync(Guid id, CancellationToken ct = default) { var x = await LoadAsync(id, false, ct); if (x is null) return null; var c = await ConditionsAsync(x, ct); return new(c.Count == 0, c); }
    public async Task<XayDungVanBanYKienUbndDto?> GuiAsync(Guid id, GuiYKienUbndRequest r, CancellationToken ct = default) { var x = await LoadAsync(id, true, ct); if (x is null) return null; EnsureNhap(x.B); var c = await ConditionsAsync(x, ct); if (c.Count > 0) throw new InvalidOperationException(string.Join(" ", c)); x.B.TrangThai = TrangThaiBoHoSo.DaGui; x.B.NgayGui = DateTime.UtcNow; var h = await db.HoSoXayDungVanBans.FirstAsync(z => z.Id == id, ct); h.BuocHienTaiId = r.BuocQuyTrinhTiepTheoId; h.TrangThaiHoSoId = r.TrangThaiHoSoTiepTheoId; await db.SaveChangesAsync(ct); return ToDto(id, x.B, x.D); }
    public async Task<bool> HuyAsync(Guid id, CancellationToken ct = default) { var x = await LoadAsync(id, true, ct); if (x is null) return false; EnsureNhap(x.B); x.B.IsDeleted = true; await db.SaveChangesAsync(ct); return true; }
    private async Task<List<string>> ConditionsAsync(Data x, CancellationToken ct) { var c = new List<string>(); if (string.IsNullOrWhiteSpace(x.D.KetLuanTongHop) && string.IsNullOrWhiteSpace(x.D.NoiDungTongHop)) c.Add("Chưa có nội dung tổng hợp hoặc kết luận."); if (!await db.BoHoSoNghiepVuTaiLieus.AnyAsync(z => z.BoHoSoNghiepVuId == x.B.Id && !z.IsDeleted, ct)) c.Add("Chưa có file tổng hợp hoặc biên bản."); return c; }
    private async Task<Data?> LoadAsync(Guid id, bool tracking, CancellationToken ct) { var b = tracking ? db.BoHoSoNghiepVus : db.BoHoSoNghiepVus.AsNoTracking(); var d = tracking ? db.HoSoXayDungVanBanYKienUbnds : db.HoSoXayDungVanBanYKienUbnds.AsNoTracking(); return await (from bo in b join detail in d on bo.Id equals detail.BoHoSoNghiepVuId where bo.HoSoXayDungVanBanId == id && bo.LoaiBoHoSo == LoaiBoHoSo.YKienThanhVienUbnd && !bo.IsDeleted select new Data(bo, detail)).FirstOrDefaultAsync(ct); }
    private static void EnsureNhap(BoHoSoNghiepVu b) { if (b.TrangThai != TrangThaiBoHoSo.Nhap) throw new InvalidOperationException("Hồ sơ không ở trạng thái nhập."); }
    private CurrentActor GetActor() { if (!user.IsAuthenticated || user.UserId is not Guid u || user.DonViId is not Guid d) throw new UnauthorizedAccessException(); return new(u, d); }
    private static XayDungVanBanYKienUbndDto ToDto(Guid h, BoHoSoNghiepVu b, HoSoXayDungVanBanYKienUbnd d) => new(h, b.Id, b.TrangThai.ToString(), d.NgayNhanYKien, d.TongSoThanhVienDuocLayYKien, d.SoDongY, d.SoKhongDongY, d.SoYKienKhac, d.KetLuanTongHop, d.NoiDungTongHop, d.NoiDungGiaiTrinh);
    private static XayDungVanBanTaiLieuDto FileDto(HoSoXayDungVanBanFile f) => new(f.Id, f.LoaiTaiLieuId, f.TenTaiLieu, f.PhienBan, f.TenFile, f.DuongDanFile, f.MimeType, f.DungLuong, f.IsCurrent, f.NgayTaiLen);
    private sealed record Data(BoHoSoNghiepVu B, HoSoXayDungVanBanYKienUbnd D); private sealed record CurrentActor(Guid UserId, Guid DonViId);
}
