// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XayDungVanBanService.Infrastructure.Persistence;

#nullable disable

namespace XayDungVanBanService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(XayDungVanBanDbContext))]
    [Migration("20261006024701_AddYKienDonVi")]
    partial class AddYKienDonVi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoHoSoNguonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocQuyTrinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonViLapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LanXuLy")
                        .HasColumnType("int");

                    b.Property<int>("LoaiBoHoSo")
                        .HasColumnType("int");

                    b.Property<string>("LyDoTraLai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiLapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungGhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoHoSoNguonId");

                    b.HasIndex("HoSoXayDungVanBanId", "BuocQuyTrinhId", "LanXuLy")
                        .IsUnique();

                    b.HasIndex("HoSoXayDungVanBanId", "LoaiBoHoSo", "TrangThai");

                    b.ToTable("BoHoSoNghiepVus");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVuTaiLieu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit");

                    b.Property<Guid>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoHoSoTaiLieuNguonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaKiemTra")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhThucThem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("HoSoXayDungVanBanFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoaiTaiLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoHoSoTaiLieuNguonId");

                    b.HasIndex("HoSoXayDungVanBanFileId");

                    b.HasIndex("BoHoSoNghiepVuId", "HoSoXayDungVanBanFileId")
                        .IsUnique();

                    b.ToTable("BoHoSoNghiepVuTaiLieus");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("DanhMucVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViChuTriSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HoSoDangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamXayDung")
                        .HasColumnType("int");

                    b.Property<Guid?>("NguoiPhuTrachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDuThaoVanBan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenHoSo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ThoiGianDuKienBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianDuKienHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TrangThaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoDangKyXayDungVanBanId");

                    b.HasIndex("MaHoSo")
                        .IsUnique();

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.HasIndex("DanhMucVanBanId", "NamXayDung");

                    b.HasIndex("NguoiPhuTrachId", "CreatedAt");

                    b.HasIndex("DonViChuTriSoanThaoId", "TrangThaiHoSoId", "CreatedAt");

                    b.HasIndex("QuyTrinhSoanThaoId", "BuocHienTaiId", "TrangThaiHoSoId");

                    b.ToTable("HoSoXayDungVanBans");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DungLuong")
                        .HasColumnType("bigint");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HashFile")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoaiTaiLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTaiLen")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiTaiLenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PhienBan")
                        .HasColumnType("int");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoXayDungVanBanId", "IsCurrent");

                    b.HasIndex("HoSoXayDungVanBanId", "LoaiTaiLieuId", "PhienBan")
                        .IsUnique();

                    b.ToTable("HoSoXayDungVanBanFiles");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanKetQuaBanHanh", b =>
                {
                    b.Property<Guid>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucVuNguoiKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CoQuanBanHanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDoKhongThongQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBanHanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCoHieuLuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungKetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoVanBan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoHoSoNghiepVuId");

                    b.ToTable("HoSoXayDungVanBanKetQuaBanHanhs");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanLichSuXuLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoHoSoNghiepVuTaiLieuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuocQuyTrinhSauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BuocQuyTrinhTruocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonViXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("HoSoXayDungVanBanFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NguoiXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBuocSau")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TenBuocTruoc")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("ThoiGianXuLy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ThuTuBuocSau")
                        .HasColumnType("int");

                    b.Property<int?>("ThuTuBuocTruoc")
                        .HasColumnType("int");

                    b.Property<Guid?>("TrangThaiSauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrangThaiTruocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BoHoSoNghiepVuId", "ThoiGianXuLy");

                    b.HasIndex("HoSoXayDungVanBanId", "ThoiGianXuLy");

                    b.ToTable("HoSoXayDungVanBanLichSuXuLys");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanSoanThao", b =>
                {
                    b.Property<Guid>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanCuXayDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DenNgayLayYKien")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhThucLayYKien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungChinhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungTongHopTiepThuGiaiTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhamViDieuChinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TongSoYKien")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TuNgayLayYKien")
                        .HasColumnType("datetime2");

                    b.HasKey("BoHoSoNghiepVuId");

                    b.ToTable("HoSoXayDungVanBanSoanThaos");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanThamDinh", b =>
                {
                    b.Property<Guid>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HanBoSung")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhThucThamDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KetQuaThamDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayGuiKetQua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThamDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiKetLuanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungKetLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungYeuCauBoSung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoHoSoNghiepVuId");

                    b.ToTable("HoSoXayDungVanBanThamDinhs");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanThamTraHdnd", b =>
                {
                    b.Property<Guid>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BanHdndThamTraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KetQuaThamTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhanKetQuaThamTra")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayNhanYKienThaoLuan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTrinhThamTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungKienNghi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungTiepThuGiaiTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungTongHopYKienThaoLuan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoHoSoNghiepVuId");

                    b.ToTable("HoSoXayDungVanBanThamTraHdnds");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanTrinhPheDuyet", b =>
                {
                    b.Property<Guid>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DonViDongGuiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MucDichTrinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatTinhTrang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayToTrinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTrinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoToTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrangXuLyBenNgoaiHeThong")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoHoSoNghiepVuId");

                    b.ToTable("HoSoXayDungVanBanTrinhPheDuyets");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanTrinhThamDinh", b =>
                {
                    b.Property<Guid>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViNhanThamDinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HanDeNghiTraKetQua")
                        .HasColumnType("datetime2");

                    b.Property<string>("LyDoTrinhLai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayGuiThamDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayToTrinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungDeNghiThamDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoToTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoHoSoNghiepVuId");

                    b.ToTable("HoSoXayDungVanBanTrinhThamDinhs");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanYKienDonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonViGopYId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungYKien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoXayDungVanBanId", "DonViGopYId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("HoSoXayDungVanBanId", "NgayNhan");

                    b.ToTable("HoSoXayDungVanBanYKienDonVis");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanYKienUbnd", b =>
                {
                    b.Property<Guid>("BoHoSoNghiepVuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanBoSungHoSo")
                        .HasColumnType("bit");

                    b.Property<string>("KetLuanTongHop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayNhanYKien")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungGiaiTrinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungTongHop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoDongY")
                        .HasColumnType("int");

                    b.Property<int?>("SoKhongDongY")
                        .HasColumnType("int");

                    b.Property<int?>("SoYKienKhac")
                        .HasColumnType("int");

                    b.Property<int?>("TongSoThanhVienDuocLayYKien")
                        .HasColumnType("int");

                    b.HasKey("BoHoSoNghiepVuId");

                    b.ToTable("HoSoXayDungVanBanYKienUbnds");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNguon")
                        .WithMany()
                        .HasForeignKey("BoHoSoNguonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBan", "HoSoXayDungVanBan")
                        .WithMany("BoHoSos")
                        .HasForeignKey("HoSoXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNguon");

                    b.Navigation("HoSoXayDungVanBan");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVuTaiLieu", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithMany("TaiLieus")
                        .HasForeignKey("BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVuTaiLieu", "BoHoSoTaiLieuNguon")
                        .WithMany()
                        .HasForeignKey("BoHoSoTaiLieuNguonId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanFile", "HoSoXayDungVanBanFile")
                        .WithMany()
                        .HasForeignKey("HoSoXayDungVanBanFileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");

                    b.Navigation("BoHoSoTaiLieuNguon");

                    b.Navigation("HoSoXayDungVanBanFile");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanFile", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBan", "HoSoXayDungVanBan")
                        .WithMany("Files")
                        .HasForeignKey("HoSoXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoXayDungVanBan");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanKetQuaBanHanh", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithOne("KetQuaBanHanh")
                        .HasForeignKey("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanKetQuaBanHanh", "BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanLichSuXuLy", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithMany("LichSuXuLys")
                        .HasForeignKey("BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBan", "HoSoXayDungVanBan")
                        .WithMany("LichSuXuLys")
                        .HasForeignKey("HoSoXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");

                    b.Navigation("HoSoXayDungVanBan");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanSoanThao", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithOne("SoanThao")
                        .HasForeignKey("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanSoanThao", "BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanThamDinh", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithOne("ThamDinh")
                        .HasForeignKey("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanThamDinh", "BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanThamTraHdnd", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithOne("ThamTraHdnd")
                        .HasForeignKey("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanThamTraHdnd", "BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanTrinhPheDuyet", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithOne("TrinhPheDuyet")
                        .HasForeignKey("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanTrinhPheDuyet", "BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanTrinhThamDinh", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithOne("TrinhThamDinh")
                        .HasForeignKey("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanTrinhThamDinh", "BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanYKienDonVi", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBan", "HoSoXayDungVanBan")
                        .WithMany("YKienDonVis")
                        .HasForeignKey("HoSoXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoXayDungVanBan");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanYKienUbnd", b =>
                {
                    b.HasOne("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", "BoHoSoNghiepVu")
                        .WithOne("YKienUbnd")
                        .HasForeignKey("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBanYKienUbnd", "BoHoSoNghiepVuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoHoSoNghiepVu");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.BoHoSoNghiepVu", b =>
                {
                    b.Navigation("KetQuaBanHanh");

                    b.Navigation("LichSuXuLys");

                    b.Navigation("SoanThao");

                    b.Navigation("TaiLieus");

                    b.Navigation("ThamDinh");

                    b.Navigation("ThamTraHdnd");

                    b.Navigation("TrinhPheDuyet");

                    b.Navigation("TrinhThamDinh");

                    b.Navigation("YKienUbnd");
                });

            modelBuilder.Entity("XayDungVanBanService.Infrastructure.Persistence.Entities.HoSoXayDungVanBan", b =>
                {
                    b.Navigation("BoHoSos");

                    b.Navigation("Files");

                    b.Navigation("LichSuXuLys");

                    b.Navigation("YKienDonVis");
                });
#pragma warning restore 612, 618
        }
    }
}
