// <auto-generated />
using System;
using DangKyXayDungVanBanService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DangKyXayDungVanBanService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DangKyXayDungVanBanDbContext))]
    [Migration("20261002043845_InitialDangKyXayDungVanBan")]
    partial class InitialDangKyXayDungVanBan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyCauHinhChuyenTrangThai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocTiepTheoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChuyenBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HanhDongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LaKetThuc")
                        .HasColumnType("bit");

                    b.Property<string>("NhomNhapLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("TrangThaiHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrangThaiTiepTheoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YeuCauFileDinhKem")
                        .HasColumnType("bit");

                    b.Property<bool>("YeuCauLyDo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuyTrinhSoanThaoId", "BuocHienTaiId", "TrangThaiHienTaiId", "HanhDongId")
                        .IsUnique();

                    b.ToTable("DangKyCauHinhChuyenTrangThais");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyHanhDongXuLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiHanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenHanhDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YeuCauFileDinhKem")
                        .HasColumnType("bit");

                    b.Property<bool>("YeuCauLyDo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaHanhDong")
                        .IsUnique();

                    b.ToTable("DangKyHanhDongXuLys");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyTrangThaiHoSo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LaTrangThaiKetThuc")
                        .HasColumnType("bit");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MauHienThi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaTrangThai")
                        .IsUnique();

                    b.ToTable("DangKyTrangThaiHoSos");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanCuDeXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaKhoiTaoQuyTrinhXayDung")
                        .HasColumnType("bit");

                    b.Property<Guid>("DonViPheDuyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DuKienThoiGianTrinh")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KetQuaPheDuyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoaiVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NamDangKy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKhoiTaoQuyTrinhXayDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungChinhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QuyTrinhXayDungTiepTheoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuCanThiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHoSo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenVanBanDuKien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrangThaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuocHienTaiId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DonViPheDuyetId");

                    b.HasIndex("DonViSoanThaoId");

                    b.HasIndex("MaHoSo")
                        .IsUnique();

                    b.HasIndex("TrangThaiHoSoId");

                    b.ToTable("DangKyXayDungVanBans");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DungLuong")
                        .HasColumnType("bigint");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiFile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyXayDungVanBanId");

                    b.ToTable("DangKyXayDungVanBanFiles");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanKetQuaPheDuyet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucVuNguoiKy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("CoQuanPheDuyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileKetQuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayVanBan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiDungKetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoVanBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenCoQuanPheDuyet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyXayDungVanBanId");

                    b.ToTable("DangKyXayDungVanBanKetQuaPheDuyets");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanLichSuXuLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChuyenBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DenBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HanhDongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LyDoTraLai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHanhDongSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungXuLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBuocDen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenBuocTu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDonViXuLy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenHanhDongSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNguoiXuLy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTrangThaiSauSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTrangThaiTruocSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("TrangThaiSauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrangThaiTruocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TuBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyXayDungVanBanId");

                    b.HasIndex("NgayXuLy");

                    b.ToTable("DangKyXayDungVanBanLichSuXuLys");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanLienKetQuyTrinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoaiVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaQuyTrinhXayDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayLienKet")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuyTrinhXayDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenQuyTrinhXayDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyXayDungVanBanId");

                    b.ToTable("DangKyXayDungVanBanLienKetQuyTrinhs");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanFile", b =>
                {
                    b.HasOne("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", "DangKyXayDungVanBan")
                        .WithMany("Files")
                        .HasForeignKey("DangKyXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyXayDungVanBan");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanKetQuaPheDuyet", b =>
                {
                    b.HasOne("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", "DangKyXayDungVanBan")
                        .WithMany("KetQuaPheDuyets")
                        .HasForeignKey("DangKyXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyXayDungVanBan");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanLichSuXuLy", b =>
                {
                    b.HasOne("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", "DangKyXayDungVanBan")
                        .WithMany("LichSuXuLys")
                        .HasForeignKey("DangKyXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyXayDungVanBan");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("KetQuaPheDuyets");

                    b.Navigation("LichSuXuLys");
                });
#pragma warning restore 612, 618
        }
    }
}
