// <auto-generated />
using System;
using DangKyXayDungVanBanService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DangKyXayDungVanBanService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DangKyXayDungVanBanDbContext))]
    [Migration("20261002090751_SeedDangKyCauHinhChuyenTrangThai")]
    partial class SeedDangKyCauHinhChuyenTrangThai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyCauHinhChuyenTrangThai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocTiepTheoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChuyenBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HanhDongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LaKetThuc")
                        .HasColumnType("bit");

                    b.Property<string>("NhomNhapLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<Guid>("TrangThaiHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrangThaiTiepTheoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YeuCauFileDinhKem")
                        .HasColumnType("bit");

                    b.Property<bool>("YeuCauLyDo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("QuyTrinhSoanThaoId", "BuocHienTaiId", "TrangThaiHienTaiId", "HanhDongId")
                        .IsUnique();

                    b.ToTable("DangKyCauHinhChuyenTrangThais");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333311"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333311"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222202"),
                            IsDeleted = false,
                            LaKetThuc = false,
                            NhomNhapLieu = "DonViSoanThao",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111102"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111102"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333311"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333311"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222202"),
                            IsDeleted = false,
                            LaKetThuc = false,
                            NhomNhapLieu = "DonViSoanThao",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111105"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111102"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333311"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333312"),
                            ChuyenBuocId = new Guid("33333333-3333-3333-3333-333333333321"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222203"),
                            IsDeleted = false,
                            LaKetThuc = false,
                            NhomNhapLieu = "DonViSoanThao",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111102"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111103"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333311"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333312"),
                            ChuyenBuocId = new Guid("33333333-3333-3333-3333-333333333321"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222203"),
                            IsDeleted = false,
                            LaKetThuc = false,
                            NhomNhapLieu = "DonViSoanThao",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111105"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111103"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333312"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333313"),
                            ChuyenBuocId = new Guid("33333333-3333-3333-3333-333333333322"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222204"),
                            IsDeleted = false,
                            LaKetThuc = false,
                            NhomNhapLieu = "DonViPheDuyet",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111103"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111104"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333312"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333311"),
                            ChuyenBuocId = new Guid("33333333-3333-3333-3333-333333333324"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222205"),
                            IsDeleted = false,
                            LaKetThuc = false,
                            NhomNhapLieu = "DonViPheDuyet",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111103"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111105"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333312"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333315"),
                            ChuyenBuocId = new Guid("33333333-3333-3333-3333-333333333325"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222206"),
                            IsDeleted = false,
                            LaKetThuc = true,
                            NhomNhapLieu = "DonViPheDuyet",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111103"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111106"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = true
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333313"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333314"),
                            ChuyenBuocId = new Guid("33333333-3333-3333-3333-333333333323"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222207"),
                            IsDeleted = false,
                            LaKetThuc = false,
                            NhomNhapLieu = "DonViSoanThao",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111104"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111107"),
                            YeuCauFileDinhKem = true,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333314"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333315"),
                            ChuyenBuocId = new Guid("33333333-3333-3333-3333-333333333326"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222208"),
                            IsDeleted = false,
                            LaKetThuc = true,
                            NhomNhapLieu = "DonViSoanThao",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111107"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111108"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444410"),
                            BuocHienTaiId = new Guid("33333333-3333-3333-3333-333333333315"),
                            BuocTiepTheoId = new Guid("33333333-3333-3333-3333-333333333315"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            HanhDongId = new Guid("22222222-2222-2222-2222-222222222209"),
                            IsDeleted = false,
                            LaKetThuc = true,
                            NhomNhapLieu = "DonViSoanThao",
                            QuyTrinhSoanThaoId = new Guid("33333333-3333-3333-3333-333333333301"),
                            TrangThai = true,
                            TrangThaiHienTaiId = new Guid("11111111-1111-1111-1111-111111111108"),
                            TrangThaiTiepTheoId = new Guid("11111111-1111-1111-1111-111111111109"),
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        });
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyHanhDongXuLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiHanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenHanhDong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("YeuCauFileDinhKem")
                        .HasColumnType("bit");

                    b.Property<bool>("YeuCauLyDo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MaHanhDong")
                        .IsUnique();

                    b.ToTable("DangKyHanhDongXuLys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "Create",
                            MaHanhDong = "TAO_MOI",
                            TenHanhDong = "Tạo mới",
                            ThuTuSapXep = 1,
                            TrangThai = true,
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "Update",
                            MaHanhDong = "CAP_NHAT_HO_SO",
                            TenHanhDong = "Cập nhật hồ sơ",
                            ThuTuSapXep = 2,
                            TrangThai = true,
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "Forward",
                            MaHanhDong = "TRINH_PHE_DUYET",
                            TenHanhDong = "Trình phê duyệt",
                            ThuTuSapXep = 3,
                            TrangThai = true,
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "Approve",
                            MaHanhDong = "PHE_DUYET",
                            TenHanhDong = "Phê duyệt",
                            ThuTuSapXep = 4,
                            TrangThai = true,
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "Return",
                            MaHanhDong = "TRA_LAI",
                            TenHanhDong = "Trả lại",
                            ThuTuSapXep = 5,
                            TrangThai = true,
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "Reject",
                            MaHanhDong = "KHONG_PHE_DUYET",
                            TenHanhDong = "Không phê duyệt",
                            ThuTuSapXep = 6,
                            TrangThai = true,
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = true
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "Update",
                            MaHanhDong = "CAP_NHAT_KET_QUA",
                            TenHanhDong = "Cập nhật kết quả",
                            ThuTuSapXep = 7,
                            TrangThai = true,
                            YeuCauFileDinhKem = true,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "Complete",
                            MaHanhDong = "HOAN_THANH",
                            TenHanhDong = "Hoàn thành",
                            ThuTuSapXep = 8,
                            TrangThai = true,
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222209"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LoaiHanhDong = "StartNextWorkflow",
                            MaHanhDong = "KHOI_TAO_QUY_TRINH_XAY_DUNG",
                            TenHanhDong = "Khởi tạo quy trình xây dựng",
                            ThuTuSapXep = 9,
                            TrangThai = true,
                            YeuCauFileDinhKem = false,
                            YeuCauLyDo = false
                        });
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyTrangThaiHoSo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LaTrangThaiKetThuc")
                        .HasColumnType("bit");

                    b.Property<string>("MaTrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MauHienThi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenTrangThai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThuTuSapXep")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaTrangThai")
                        .IsUnique();

                    b.ToTable("DangKyTrangThaiHoSos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = false,
                            MaTrangThai = "MOI_TAO",
                            MauHienThi = "gray",
                            TenTrangThai = "Mới tạo",
                            ThuTuSapXep = 1,
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = false,
                            MaTrangThai = "DANG_SOAN_THAO",
                            MauHienThi = "blue",
                            TenTrangThai = "Đang soạn thảo",
                            ThuTuSapXep = 2,
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = false,
                            MaTrangThai = "DA_TRINH_PHE_DUYET",
                            MauHienThi = "orange",
                            TenTrangThai = "Đã trình phê duyệt",
                            ThuTuSapXep = 3,
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = false,
                            MaTrangThai = "DA_PHE_DUYET",
                            MauHienThi = "green",
                            TenTrangThai = "Đã phê duyệt",
                            ThuTuSapXep = 4,
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = false,
                            MaTrangThai = "BI_TRA_LAI",
                            MauHienThi = "red",
                            TenTrangThai = "Bị trả lại",
                            ThuTuSapXep = 5,
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = true,
                            MaTrangThai = "KHONG_PHE_DUYET",
                            MauHienThi = "red",
                            TenTrangThai = "Không phê duyệt",
                            ThuTuSapXep = 6,
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = false,
                            MaTrangThai = "DA_CAP_NHAT_KET_QUA",
                            MauHienThi = "cyan",
                            TenTrangThai = "Đã cập nhật kết quả",
                            ThuTuSapXep = 7,
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = true,
                            MaTrangThai = "HOAN_THANH",
                            MauHienThi = "green",
                            TenTrangThai = "Hoàn thành",
                            ThuTuSapXep = 8,
                            TrangThai = true
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            CreatedAt = new DateTime(2026, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            LaTrangThaiKetThuc = true,
                            MaTrangThai = "DA_CHUYEN_QUY_TRINH_XAY_DUNG",
                            MauHienThi = "purple",
                            TenTrangThai = "Đã chuyển quy trình xây dựng",
                            ThuTuSapXep = 9,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocHienTaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanCuDeXuat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DaKhoiTaoQuyTrinhXayDung")
                        .HasColumnType("bit");

                    b.Property<Guid>("DonViPheDuyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DuKienThoiGianTrinh")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KetQuaPheDuyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoaiVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NamDangKy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKhoiTaoQuyTrinhXayDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungChinhSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("QuyTrinhSoanThaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("QuyTrinhXayDungTiepTheoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuCanThiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHoSo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenVanBanDuKien")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrangThaiHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BuocHienTaiId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DonViPheDuyetId");

                    b.HasIndex("DonViSoanThaoId");

                    b.HasIndex("MaHoSo")
                        .IsUnique();

                    b.HasIndex("TrangThaiHoSoId");

                    b.ToTable("DangKyXayDungVanBans");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DungLuong")
                        .HasColumnType("bigint");

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiFile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyXayDungVanBanId");

                    b.ToTable("DangKyXayDungVanBanFiles");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanKetQuaPheDuyet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChucVuNguoiKy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("CoQuanPheDuyetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileKetQuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayVanBan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiKy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiDungKetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoVanBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenCoQuanPheDuyet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyXayDungVanBanId");

                    b.ToTable("DangKyXayDungVanBanKetQuaPheDuyets");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanLichSuXuLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChuyenBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DenBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HanhDongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LyDoTraLai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaHanhDongSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungXuLy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBuocDen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenBuocTu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDonViXuLy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenHanhDongSnapshot")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenNguoiXuLy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTrangThaiSauSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenTrangThaiTruocSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("TrangThaiSauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrangThaiTruocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TuBuocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyXayDungVanBanId");

                    b.HasIndex("NgayXuLy");

                    b.ToTable("DangKyXayDungVanBanLichSuXuLys");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanLienKetQuyTrinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DangKyXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoSoXayDungVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoaiVanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaQuyTrinhXayDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayLienKet")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuyTrinhXayDungId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenQuyTrinhXayDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DangKyXayDungVanBanId");

                    b.ToTable("DangKyXayDungVanBanLienKetQuyTrinhs");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanFile", b =>
                {
                    b.HasOne("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", "DangKyXayDungVanBan")
                        .WithMany("Files")
                        .HasForeignKey("DangKyXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyXayDungVanBan");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanKetQuaPheDuyet", b =>
                {
                    b.HasOne("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", "DangKyXayDungVanBan")
                        .WithMany("KetQuaPheDuyets")
                        .HasForeignKey("DangKyXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyXayDungVanBan");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBanLichSuXuLy", b =>
                {
                    b.HasOne("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", "DangKyXayDungVanBan")
                        .WithMany("LichSuXuLys")
                        .HasForeignKey("DangKyXayDungVanBanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKyXayDungVanBan");
                });

            modelBuilder.Entity("DangKyXayDungVanBanService.Infrastructure.Persistence.Entities.DangKyXayDungVanBan", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("KetQuaPheDuyets");

                    b.Navigation("LichSuXuLys");
                });
#pragma warning restore 612, 618
        }
    }
}
