// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThiHanhPhapLuatService.Infrastructure.Persistence;

#nullable disable

namespace ThiHanhPhapLuatService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ThiHanhPhapLuatDbContext))]
    [Migration("20261006142721_AddTongHopLanChot")]
    partial class AddTongHopLanChot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("thpl")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.BaoCaoTienDoThiHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoKhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KienNghi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayBaoCao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PhanCongThiHanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TyLeHoanThanh")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NoiDungKeHoachId", "KyBaoCao", "CreatedAt");

                    b.ToTable("BaoCaoTienDoThiHanhs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.BaoCaoTongHopChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaoCaoTongHopThiHanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoKhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KienNghi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanChot")
                        .HasColumnType("int");

                    b.Property<Guid>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TyLeHoanThanh")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaoCaoTongHopThiHanhId", "NoiDungKeHoachId", "LanChot")
                        .IsUnique();

                    b.ToTable("BaoCaoTongHopChiTiets", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.BaoCaoTongHopThiHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DenNgay")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KyBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaBaoCao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayChot")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiChotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoLieuTongHopJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("TuNgay")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaBaoCao")
                        .IsUnique();

                    b.HasIndex("KeHoachId", "KyBaoCao")
                        .IsUnique();

                    b.ToTable("BaoCaoTongHopThiHanhs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.DanhGiaThiHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaoCaoTienDoThiHanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQuaDanhGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NguoiDanhGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrangThaiSauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DanhGiaThiHanhs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.KeHoachCanCuPhapLy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoKyHieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TrichYeu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("VanBanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("KeHoachCanCuPhapLys", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.KeHoachThiHanhPhapLuat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DenNgay")
                        .HasColumnType("date");

                    b.Property<Guid>("DonViChuTriId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaKeHoach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MucTieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<Guid?>("NguoiPhuTrachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhamVi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKeHoach")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("TuNgay")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaKeHoach")
                        .IsUnique();

                    b.HasIndex("DonViChuTriId", "TrangThaiId", "Nam");

                    b.ToTable("KeHoachThiHanhPhapLuats", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.LichSuNhacViecThiHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViNhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KenhGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiNhacViec")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("NguoiNhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NoiDungKeHoachId", "LoaiNhacViec", "ThoiGianGui");

                    b.ToTable("LichSuNhacViecThiHanhs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.LichSuXuLyThiHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DonViXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NguoiXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ThoiGianXuLy")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TrangThaiSauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TrangThaiTruocId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KeHoachId", "ThoiGianXuLy");

                    b.ToTable("LichSuXuLyThiHanhs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.NoiDungKeHoach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ChiTieu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("HanHoanThanh")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("KeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaNoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<Guid>("TrangThaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TyLeHoanThanh")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KeHoachId", "MaNoiDung")
                        .IsUnique();

                    b.HasIndex("KeHoachId", "TrangThaiId", "HanHoanThanh");

                    b.ToTable("NoiDungKeHoachs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.PhanCongThiHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CanBoDuocGiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DonViDuocGiaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("HanThucHien")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MucDoUuTien")
                        .HasColumnType("int");

                    b.Property<Guid>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhanCongThiHanhs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.TepDinhKemThiHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaoCaoTienDoThiHanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("KeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PhienBan")
                        .HasColumnType("int");

                    b.Property<string>("TenTep")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KeHoachId", "LoaiTaiLieu", "PhienBan");

                    b.HasIndex("NoiDungKeHoachId", "BaoCaoTienDoThiHanhId", "IsCurrent");

                    b.ToTable("TepDinhKemThiHanhs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.YeuCauBoSungThiHanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaoCaoTienDoThiHanhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("HanBoSung")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NoiDungKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDungYeuCau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YeuCauBoSungThiHanhs", "thpl");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.NoiDungKeHoach", b =>
                {
                    b.HasOne("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.KeHoachThiHanhPhapLuat", "KeHoach")
                        .WithMany("NoiDungs")
                        .HasForeignKey("KeHoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeHoach");
                });

            modelBuilder.Entity("ThiHanhPhapLuatService.Infrastructure.Persistence.Entities.KeHoachThiHanhPhapLuat", b =>
                {
                    b.Navigation("NoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
