// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using QuanTriHeThongService.Infrastructure.Persistence;

#nullable disable

namespace QuanTriHeThongService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuanTriHeThongDbContext))]
    [Migration("20260930093000_AddSystemInfoMenuLayout")]
    partial class AddSystemInfoMenuLayout
    {
    }
}
